"""Creator Docs (/docs): one page per feature, rendered by templates/help.html.

The platform consoles already explain every control in their own setup wizards
(js/*-guide.js). Their help pages render those same steps (`guide`), so the
console and its help page can never disagree; only the tips are written here.
"""

GROUPS = ['Start here', 'Content creation', 'Chat & sales', 'Platforms', 'Account']

PAGES = {
    'getting-started': {
        'group': 'Start here',
        'title': 'Getting started',
        'summary': 'The order to set things up in, from an empty account to a persona earning on a platform.',
        'steps': [
            'Create a <b>character</b> in Character Creator: her face, body and approved photos. Every photo made later is generated from her.',
            'Make photos of her in the <b>Generation Studio</b> and press <b>Keep</b> on the good ones. Kept photos go to the Content Vault.',
            'Create a <b>persona</b> (subscription plans): her voice, backstory and how she moves a fan from hello to a sale.',
            'Open <b>Chat</b> and talk to her yourself until she sounds right.',
            'Connect a <b>platform</b> (Fanvue, Telegram, X, Threads, Instagram, Discord) and switch her on.',
            'Publish your <b>Link in bio</b> page and put it in your social bios.',
        ],
        'options_title': 'Good to know',
        'options': [
            ('Free plan', 'Characters, the studio, token top-ups and one link-in-bio page. Chatbot features show as <i>Subscribers only</i>.'),
            ('Paid plans', 'Everything on Free, plus personas, chat, the planner and every platform.'),
            ('Search box', 'The dashboard sidebar search finds any screen by keyword, e.g. "ppv" or "schedule".'),
            ('Guide button', 'Most screens have a <b>Guide</b> that walks you through the real controls one step at a time.'),
        ],
        'tips': [
            'Build the character first. A persona linked to an approved character fills in her looks for you.',
            'Nothing a generation makes reaches a fan until you keep it.',
            'Test every change in Chat before a fan sees it.',
        ],
    },
    'plans-and-tokens': {
        'group': 'Start here',
        'title': 'Plans & tokens',
        'summary': 'What each plan includes, how tokens are spent and how to top up.',
        'steps': [
            'Open <b>Tokens</b> in the top bar to see your balance and the price list.',
            'Pick a pack and pay by card or crypto. Tokens land as soon as the payment clears.',
            'Every generate button shows its token price before you click.',
        ],
        'options': [
            ('Free', '15 one-time tokens. Studio, characters, one link-in-bio page.'),
            ('Starter', '75 tokens a month, personas and chat.'),
            ('Pro', '300 tokens a month.'),
            ('Agency', '1,000 tokens a month.'),
            ('Monthly allowance', 'Arrives at the start of each month and expires at the end of it. It is always spent before tokens you bought.'),
            ('Bought tokens', 'Packs of 100, 200, 300, 500, 1,000, 2,000 and 5,000. They never expire.'),
            ('Refunds', 'A generation that fails returns its tokens to the bucket they came from.'),
        ],
        'tips': [
            'Bigger packs cost less per token.',
            'Generate one photo to test a prompt, then raise <b>How many</b> once it looks right.',
            'Upgrade from <b>Upgrade</b> in the top bar; your bought tokens carry over.',
        ],
    },
    'characters': {
        'group': 'Content creation',
        'title': 'Character Creator',
        'summary': 'Her fixed look. A character drives every photo made for her, so she always looks like herself.',
        'steps': [
            'Press <b>+ New character</b>, or <b>I already have her</b> to use photos you own.',
            '<b>Basics:</b> name, age (18 or over) and explicitness level (SFW, Topless, Explicit).',
            '<b>Her face:</b> build it from drawings, or blend reference photos into a new face. Press <b>Generate face options</b>.',
            'Tap the best option, run the <b>Feature check</b> and press <b>Approve face</b>. Nothing else unlocks until the face is approved.',
            'Optional: add three more face angles for extra control.',
            '<b>Body profile:</b> start from a preset or match reference bodies, then fine-tune under Advanced.',
            'Generate each remaining photo with its own button and approve one per step.',
            'Under <b>Her persona</b>, give her a chatting side, or press <b>Open the studio</b> to create content.',
        ],
        'sections': [{'id': 'list',
          'title': 'Your characters',
          'shot': 'characters-list',
          'body': 'Every character you made. Start one with <b>+ New character</b>, or <b>I already have her</b> to '
                  'turn photos you own into her approved look without generating anything.',
          'rows': [('Her face', 'Pick her features, then choose and approve a face.'),
                   ('Her body', 'Set her shape and approve a few set photos.'),
                   ('Ready', 'Accept her and link her to a persona.')]},
         {'id': 'basics',
          'title': 'Basics: who is she?',
          'shot': 'characters-basics',
          'body': 'The first step. The left rail shows every step and how far along she is; locked steps open once '
                  'the step before is approved.',
          'rows': [('Name', 'Her name. Needed to continue.'),
                   ('Age', '18 or over. Every prompt states she is a fictional adult of this age.'),
                   ('Explicitness level',
                    '<b>SFW</b> (clothed photos only), <b>Topless</b> or <b>Explicit</b>. Decides which intimate '
                    'steps exist.'),
                   ('Notes (optional)', 'Anything you want to remember about her.'),
                   ('Save / Save & continue', 'Save keeps the draft; Save & continue moves to her face.')],
          'tips': ['Pick the level you will really need; it decides which steps you have to approve.']},
         {'id': 'face',
          'title': 'Her face',
          'shot': 'characters-face',
          'body': 'Tap the drawing that fits each feature: face shape, eyes, eyebrows, nose, lips, makeup, '
                  'cheekbones and more. Then generate face options, pick one, run the check and approve.',
          'rows': [('Create with the builder', 'Pick every feature from drawings.'),
                   ('Blend reference photos',
                    'The new face mixes features from several photos and is none of them. Confirm you have the '
                    'rights and everyone is 18+.'),
                   ('Options per try', 'How many faces each Generate makes. More costs more tokens.'),
                   ('Feature check',
                    'An automatic check that she looks adult and matches your picks. Tick all matches to approve.'),
                   ('Face angles (optional)', 'Three-quarter, profile and smiling angles for extra control.'),
                   ('Adjust the crop',
                    'Drag the box to reframe a photo, then use it as the photo or as a reference.')],
          'tips': ['Spend your effort here; every later photo copies this face.',
                   'Options you do not approve delete themselves after 3 days.']}],
        'tips': [
            'Spend your effort on the face. Every later photo copies it.',
            'Pick a clear, front-facing, evenly lit face option.',
            'Options you do not approve delete themselves after 3 days.',
            'Characters are unlimited on every plan; only personas count against your plan.',
        ],
    },
    'studio': {
        'group': 'Content creation',
        'title': 'Generation Studio',
        'summary': 'Make photos and clips of her. The price is on the button before you click.',
        'steps': [
            'Pick the <b>Rating</b>: Safe or Explicit.',
            '<b>1 · Engine:</b> choose the model that makes the photo.',
            '<b>2 · Character:</b> choose whose photos these are and where her look comes from.',
            '<b>3 · Prompt:</b> pick the place, what is happening and her expression; the direction fills itself in.',
            '<b>4 · Size & generate:</b> choose size, shape and how many, then press <b>Generate</b>.',
            'Results land unapproved. Press <b>Keep</b> to move a photo into her vault, or <b>Drop</b>. The rest delete themselves after 3 days.',
        ],
        'sections': [
            {'id': 'rating', 'title': 'Rating', 'shot': 'studio-rating',
             'body': 'The first choice. <b>Safe</b> or <b>Explicit</b> decides which jobs, shots and words are allowed for this photo. Safe-work shots never use explicit photos or words of her.',
             'tips': ['Pick the rating first; changing it later resets choices that no longer fit.']},
            {'id': 'jobs', 'title': 'Jobs: photo or video', 'shot': 'studio-jobs',
             'body': 'What you are making. <b>Photos</b> makes stills from your choices. Under Video, <b>Photo to Video</b> brings one of her kept photos to life. Tiles marked <b>Soon</b> are not open yet.',
             'rows': [
                 ('Photos', 'Stills from a prompt, with her look held by her character or reference photos.'),
                 ('Photo to Video', 'One of her approved photos, animated into a short clip.'),
                 ('Reel, Swap, Extend, Multi-reference', 'Coming soon.'),
             ]},
            {'id': 'engine', 'title': '1 · Engine', 'shot': 'studio-engine',
             'body': 'The model that draws the photo. The price per photo is shown on each one; holding her face costs nothing extra.',
             'rows': [
                 ('Creative Pro', 'Bold, stylised ideas. Cheapest.'),
                 ('True Life', 'Natural, everyday moments, made fast.'),
                 ('Ultra Realism', 'The most lifelike skin and light. Costs the most.'),
             ],
             'tips': ['Test a new idea on a cheaper engine, then make the final on Ultra Realism.']},
            {'id': 'character', 'title': '2 · Character', 'shot': 'studio-character',
             'body': 'Whose photos these are. Pick her character, and choose where her look comes from. The empty <b>Her face</b> and <b>Her body</b> slots take extra reference photos from her vault.',
             'rows': [
                 ('Whose photos are we generating?', 'The character (and persona) the photo is of.'),
                 ('Her look comes from', '<b>Her character</b> (her approved build), <b>Face & body photos</b> (the slots below), or <b>Both</b>.'),
                 ('Her face / Her body', 'Up to 14 reference photos each, picked from the vault. Clear, well-lit photos work best.'),
             ],
             'tips': ['Use <b>Her character</b> once she is approved; it gives the most consistent face.']},
            {'id': 'shot', 'title': '3 · Prompt: the shot', 'shot': 'studio-shot',
             'body': 'Build the scene from menus; the prompt is written for you.',
             'rows': [
                 ('Where is she', 'Anywhere, Bedroom, Bathroom, Hotel, Living room, Kitchen, Poolside, Beach, Cafe, Gym, Car, Fitting room, Street, Rooftop bar and more.'),
                 ('What is happening (Explicit)', 'The act or pose, added on top of the place. <i>Write your own…</i> for your words.'),
                 ('Content type', 'Portrait, Face close-up, Waist up, Full body, Candid or Mirror selfie.'),
                 ('Style', 'Any, Candid, Mirror selfie, Photoshoot or POV selfie.'),
                 ('Expression', 'Auto, Soft smile, Big smile, Laughing, Smirk, Wink, Kissy pout, Tongue out, Sultry, Biting lip, Shy and more.'),
                 ('Zoom', 'Auto, Close, Medium, Wide or Far.'),
                 ('Or use a photo of the place', 'A vault photo of a room or location. It wins over "Where is she"; only the place is copied, never people in it.'),
                 ('What she\'s doing', 'Fills in from your choices. <b>✦ Suggest</b> gives a new idea, or type your own.'),
             ],
             'tips': ['Change one menu at a time so you learn what each does.', 'Full body plus a place photo gives the most believable scenes.']},
            {'id': 'wears', 'title': '3 · Prompt: what she wears', 'shot': 'studio-wears',
             'body': 'Describe the outfit, or pick an outfit photo from the vault. This overrides every other outfit in the scene. From a photo, only the clothes are copied, never the person.',
             'tips': ['Use an outfit photo when the clothes must match exactly across a set.']},
            {'id': 'camera', 'title': '3 · Prompt: camera & look', 'shot': 'studio-camera',
             'body': 'How the photo looks, as if taken on a real device.',
             'rows': [
                 ('Phone camera', 'Auto, iPhone 16 Pro, iPhone 14, iPhone 11, front camera, Samsung S24 Ultra, S22, Pixel 8, Budget Android or Disposable camera.'),
                 ('Lighting', 'Auto, Candlelight, Daylight, Dusk neon, Golden hour, Morning sun, Phone flash, Shower light, Studio or Warm low.'),
                 ('Photo quality', 'Real phone photo, Clean flagship phone or Professional shoot.'),
                 ('Phone look', 'Free grain, soft lens and glow: Off, Light, Medium or Heavy.'),
                 ('Smudges and dust', 'Marks on the lens or mirror for extra realism.'),
             ],
             'tips': ['For feed-style content, "Real phone photo" with a Light phone look reads most natural.']},
            {'id': 'advanced', 'title': '3 · Prompt: advanced', 'shot': 'studio-advanced',
             'body': 'Open <b>Advanced</b> to see the exact prompt. <b>Write the prompt</b> rebuilds it from your choices; your own edits stay when a choice changes.',
             'rows': [
                 ('Prompt', 'The full instruction sent to the engine. Edit freely.'),
                 ('Keep out of the shot', 'Things to avoid, e.g. sunglasses, jewellery, other people.'),
                 ('Always added', 'A safety baseline that is always included and can\'t be removed.'),
             ]},
            {'id': 'size', 'title': '4 · Size & generate', 'shot': 'studio-size',
             'body': 'Set the output, check the price, press <b>Generate</b>. Results appear below the button.',
             'rows': [
                 ('Size', '2K or 4K.'),
                 ('How many', '1, 2, 4 or 6 photos per click.'),
                 ('Frame shape', '1:1, 4:5, 5:4, 3:4, 4:3, 2:3, 3:2, 9:16, 16:9 or 21:9. Same price whichever you pick.'),
                 ('Price box', 'Total tokens and the money equivalent for this click.'),
             ],
             'tips': ['Generate 1 to test, then 4 once it looks right.', '9:16 for Stories and Reels, 4:5 for feed posts.']},
            {'id': 'video', 'title': 'Photo to Video', 'shot': 'studio-video',
             'body': 'Pick the Photo to Video tile. A clip always starts from a photo you already kept, so the first frame is her.',
             'rows': [
                 ('Photo to animate', '<b>Choose from vault</b>: the kept photo the clip starts from.'),
                 ('Motion', 'Describe the movement, e.g. "she turns towards the camera and smiles".'),
                 ('Presets', 'One-click motions: Hair flip, Wink & kiss, Slow turn.'),
                 ('Motion clip (optional)', 'Upload a clip and her photo copies its movement. The clip is never shown to a fan.'),
                 ('Clip size / Seconds', '480p, 720p or 1080p, and 2 to 15 seconds. Both change the price.'),
                 ('Sound', 'Keep, generate or upload audio for the clip.'),
             ],
             'tips': ['Short, simple motions look most natural.', 'Start from a sharp photo with her face clearly visible.']},
            {'id': 'kept', 'title': 'Results and kept photos', 'shot': 'studio-kept',
             'body': 'New results land unapproved. Press <b>Keep</b> to move one into her vault, or <b>Drop</b>. Anything not kept deletes itself after 3 days. Kept photos are listed here and can be used in chats, posts and clips.',
             'rows': [
                 ('Select / Select all / Clear', 'Pick several kept photos for a bulk action.'),
                 ('Upload to Fanvue', 'Send selected photos to your Fanvue vault (subscribers only).'),
                 ('Undress', 'Open a kept photo in Undress.'),
             ],
             'tips': ['Keep only your best shots so the vault stays easy to search.']},
        ],
        'tips': [
            'Set the rating first; it narrows everything else.',
            'Generate one, check it, then raise How many.',
            'Use an outfit photo when the clothes must match exactly.',
            'Keep only your best shots so the vault stays easy to search.',
            'Press <b>Guide</b> at the top for a tour of the real panels.',
        ],
    },
    'undress': {
        'group': 'Content creation',
        'title': 'Undress',
        'early': True,
        'summary': 'Turn a photo of her into an undressed version. Private to your account.',
        'steps': [
            '<b>Add a photo:</b> drop it on the page, or press Undress on a kept photo in the studio.',
            '<b>Click Undress.</b> It takes about a minute; the result appears next to its original.',
            '<b>Download or delete.</b> Select several photos for bulk actions.',
        ],
        'sections': [{'id': 'undress',
          'title': 'The Undress page',
          'shot': 'undress',
          'body': 'Add photos, press Undress on one, then keep or delete the result. Each photo costs the token '
                  'price shown at the top.',
          'rows': [('+ Upload / + From vault', 'Add a photo from your device or from her vault.'),
                   ('Filter / Sort / Cards / List', 'Find and arrange your photos.'),
                   ('Select', 'Pick several for Download or Delete.')]}],
        'tips': [
            'Use photos of your own character only.',
            'A clear, well-lit, full-body photo gives the best result.',
        ],
    },
    'vault': {
        'group': 'Content creation',
        'title': 'Content Vault',
        'summary': 'Every approved photo and clip: uploads plus whatever you kept from the studio. The only place sends and posts pick from.',
        'steps': [
            'Open <b>Content Vault</b> from the sidebar.',
            'Upload files, or keep generations in the studio to fill it.',
            'Rate each item <b>Safe for work</b> or <b>Explicit</b>, and sort it into folders.',
        ],
        'sections': [{'id': 'vault',
          'title': 'Her vault',
          'shot': 'vault',
          'body': 'Every approved photo and clip for her. It is the only place chats, posts and clips pick media '
                  'from.',
          'rows': [('+ Upload', 'Add your own photos and clips.'),
                   ('Search', 'Find media by name.'),
                   ('Filter', 'Safe for work, Explicit, Unrated, favourites.'),
                   ('Sort', 'Newest or oldest first.'),
                   ('Cards / List', 'Switch the layout.'),
                   ('+ Folder', 'Group media by set or shoot.')]}],
        'tips': [
            'Rate everything. Unrated media can land in the wrong place, and safe-work channels only use safe-work media.',
            'Use folders per set or per shoot so pickers stay quick.',
            'Unreviewed generations never appear here, so nothing unchecked reaches a fan.',
        ],
    },
    'personas': {
        'group': 'Chat & sales',
        'title': 'Personas',
        'summary': 'Her chatting side: voice, backstory and how she moves a fan from hello to a sale.',
        'steps': [
            'Press <b>+ New Persona</b> and name her. The setup walks you through four stages, one question at a time.',
            '<b>Who she is:</b> name, age, personality, backstory and looks.',
            '<b>How she talks:</b> writing style, warmth, interests, reply speed and flirt pace.',
            '<b>How she earns:</b> how far she goes and where fans should end up.',
            '<b>Go live:</b> press <b>Test Chat</b>, then <b>Save & Deploy</b>. Nothing is published until you do.',
        ],
        'sections': [{'id': 'list',
          'title': 'Your personas',
          'shot': 'personas-list',
          'body': 'All your personas as cards with how complete each one is. Search, filter, sort and switch between '
                  'cards and list. Press <b>Open</b> to edit one, or <b>+ New persona</b>.'},
         {'id': 'name',
          'title': 'Who is she?',
          'shot': 'personas-0',
          'body': 'Setup asks one question per step; the live chat preview on the right updates as you type.',
          'rows': [('Display name / Age / Gender', 'What every fan sees first. 18 or over.'),
                   ('Location',
                    "Leave blank and she keeps it vague. <b>Always match the fan's location</b> makes her say she "
                    'lives near the fan.')]},
         {'id': 'personality',
          'title': "What's she like?",
          'shot': 'personas-1',
          'body': '<b>Personality archetype</b>: Deadpan / Dry, Bubbly / Sweet, Dominant / Edgy, Girl-Next-Door, '
                  'Mysterious / Dark, Playful / Teasing or Intellectual / Witty. It shapes every message she sends.'},
         {'id': 'story',
          'title': "What's her story?",
          'shot': 'personas-2',
          'body': 'Two or three sentences: job, city, vibe. <b>Randomize</b> fills one in, <b>Build with AI</b> '
                  'interviews you and writes it.'},
         {'id': 'looks',
          'title': 'What does she look like?',
          'shot': 'personas-3',
          'rows': [('Profile picture', 'Upload one, or it uses the first of her photos.'),
                   ('Appearance', 'Free text that replaces the boxes below. Linking a character fills these in.'),
                   ('Body type / Chest size / Hair / Eyes / Style',
                    'Her look in words, used in every generated photo.'),
                   ('Her phone / Her voice / Never in her photos',
                    'Phone shown in selfies, how she sounds in clips, and things struck out of every photo.')]},
         {'id': 'writing',
          'title': 'How does she write?',
          'shot': 'personas-4',
          'rows': [('Speech style rules',
                    'Slang, punctuation and quirks. <b>Generate</b> writes them from her personality.'),
                   ('Reply length', 'Short (1–2 sentences), medium or long.'),
                   ('Emoji use', 'None, rare, some or lots.'),
                   ('Write in lowercase', 'Off gives normal capitalisation.')],
          'tips': ['Short, lowercase, little emoji reads most like a real person.']},
         {'id': 'warmth',
          'title': 'How warm is she?',
          'shot': 'personas-5',
          'rows': [('Warmth level', 'Cold, Distant, Friendly, Warm or Affectionate.'),
                   ('Question frequency',
                    'Rarely, sometimes, often or very often she asks the fan something back.')]},
         {'id': 'interests',
          'title': 'What does she love talking about?',
          'shot': 'personas-6',
          'body': 'Comma-separated topics she steers back to, so chats never run dry. <b>Generate</b> or '
                  '<b>Randomize</b> suggests some.'},
         {'id': 'speed',
          'title': 'How fast does she reply?',
          'shot': 'personas-7',
          'rows': [('Reply speed',
                    'Pause before she starts typing on your web chat: instant, fast, natural or slow.'),
                   ('Typing speed', 'How long the typing bubble runs: fast, natural or slow.')],
          'tips': ['Natural or slow feels human; instant feels like a bot.']},
         {'id': 'flirt',
          'title': 'How fast does she flirt?',
          'shot': 'personas-8',
          'body': '<b>Flirt escalation pace</b>: slow (over many chats), moderate, fast (one chat) or instant. A '
                  'slow burn keeps fans for weeks; instant converts faster but burns out sooner.'},
         {'id': 'nsfw',
          'title': 'How far does she go?',
          'shot': 'personas-9',
          'body': '<b>Enable NSFW / Adult content</b>, then the <b>NSFW level</b> sets her ceiling: suggestive, '
                  'moderate or explicit. She works up to it gradually.'},
         {'id': 'offer',
          'title': 'Where do you want fans to end up?',
          'shot': 'personas-10',
          'rows': [('Conversion triggers',
                    'When and how she brings up your offer. <b>Regenerate</b> writes them; edit freely.'),
                   ('CTA destination URL / label', 'Your paid page and the line she says before it.'),
                   ('When a fan asks for spicy content',
                    'Off, normal, fast (link in the next reply or two) or instant (same reply).'),
                   ('Release an explicit preview after',
                    'After this many asks she attaches a preview photo. 0 = off.'),
                   ('Free trial / promo code',
                    'Sent instead to fans who never opened the paid link, until the code expires.')],
          'tips': ['Write triggers as moments, not sales lines: "when he asks what I did today".']}],
        'tips': [
            'Short replies, little emoji and lowercase read most like a real person.',
            'Slow or natural reply speed feels human; instant feels like a bot.',
            'A slow burn keeps fans chatting for weeks; instant converts faster but burns out sooner.',
            'Write conversion triggers as moments, not sales lines: "when he asks what I did today".',
            'Use <b>Preview Prompt</b> to see exactly what she is told.',
        ],
    },
    'chat': {
        'group': 'Chat & sales',
        'title': 'Chat',
        'summary': 'Talk to your persona exactly as a fan would, before any fan does.',
        'steps': [
            'Open <b>Chat</b> from the sidebar and pick the persona.',
            'Write the way your fans write, including the questions they ask.',
            'Change a setting in the persona builder, save, and chat again to compare.',
        ],
        'options': [
            ('Live Chat / System Prompt / Funnel', 'Tabs in the builder preview: the chat, what she is told, and which funnel stage the chat is in.'),
            ('Funnel stages', 'Warm, Engage, Intrigue, Tease, Offer, Close. Your flirt pace sets how fast she moves.'),
        ],
        'tips': [
            'Try the awkward messages too: rude fans, "are you a bot?", price questions.',
            'If she sells too early, slow the flirt pace or the spicy-content setting.',
        ],
    },
    'planner': {
        'group': 'Chat & sales',
        'title': 'Content Planner',
        'summary': 'Plan a week of posts across your channels in one calendar.',
        'steps': [
            'Press <b>Plan the week</b> for a full week drafted for you, or <b>New post</b> for one.',
            'Pick the <b>Channels</b> and <b>When</b>; add more dates with <b>+ Add date</b>.',
            'Write the post, or press <b>✨ Write it</b>.',
            'Add media from the vault, or press <b>🎨 Create media</b> to make it from the post text.',
            'Press <b>Save changes</b>, or <b>Post now</b>.',
        ],
        'sections': [{'id': 'week',
          'title': 'The week',
          'shot': 'planner-week',
          'body': 'Every planned post for one persona, day by day. Use the arrows to change week.',
          'rows': [('Persona', 'Whose posts you are planning.'),
                   ('Refresh', 'Reload the week.'),
                   ('New post', 'Write one post by hand: channels, date, text, media, then Save or Post now.'),
                   ('Clear week', 'Remove every planned post this week.'),
                   ('Queued / posted / failed', 'Counts for this week.')]},
         {'id': 'post',
          'title': 'New post',
          'shot': 'planner-post',
          'body': 'One post for one or more channels. Nothing exists until you add it to the week or post it.',
          'rows': [('Channels', 'X, Threads, Fanvue, Fanvue mass DM, Instagram. TikTok and Reddit are by hand. Each channel gets its own copy, trimmed to its limit.'),
                   ('When / + Add date', 'The date and time it goes out. Add dates to post it more than once.'),
                   ('Post', 'The text, with a character counter for the channel.'),
                   ('✨ Write it', 'Type an angle and she writes the post. Auto, SFW or NSFW sets how spicy; Copy copies it.'),
                   ('Media', 'Up to 4 images or videos. <b>Choose from vault</b>, or <b>🎨 Create media</b> to make them from the post text.'),
                   ('Close / Post now / Add to the week', 'Discard, send it right away, or queue it at the chosen time.')],
          'tips': ['Write it reads an attached picture and writes about what is in it, so attach media first.']},
         {'id': 'plan',
          'title': 'Plan the week',
          'shot': 'planner-plan',
          'body': 'Drafts a full week for you. Tick the channels and set how many posts each gets, then press '
                  '<b>Plan it</b>.',
          'rows': [('Channels',
                    'X, Threads, Fanvue, Instagram, TikTok, Reddit. "By hand" channels come back to you to post '
                    'yourself.'),
                   ('Media', 'How many of the posts carry a photo or clip.'),
                   ('Same post everywhere', 'One text for every channel instead of one each.')],
          'tips': ['Plan on Monday, then only tweak.', 'Mix free posts with paid ones.']}],
        'tips': [
            'Plan the week on Monday, then only tweak.',
            'Mix free posts with paid ones so followers keep opening them.',
            'Keep safe-work channels safe-work; the planner shows each post\'s rating.',
        ],
    },
    'link-in-bio': {
        'group': 'Chat & sales',
        'title': 'Link in bio',
        'summary': 'One page for your social bios with all your links, on a neutral domain.',
        'steps': [
            'Open <b>Link in bio</b> from the sidebar.',
            '<b>Links:</b> add links, headers, text and a <b>Chat with me</b> button.',
            '<b>Profile:</b> picture, name and bio.',
            '<b>Style:</b> theme, background, buttons and fonts.',
            'Press <b>Save</b>, then <b>Copy link</b> and paste it into your Instagram, TikTok or X bio.',
        ],
        'sections': [{'id': 'links',
          'title': 'Links',
          'shot': 'bio-links',
          'body': 'Your page link, its stats and the buttons on it. The phone on the right previews the page live.',
          'rows': [('Your link', '<b>Copy link</b> and put it in your Instagram, TikTok or X bio.'),
                   ('Page views / Button clicks / Click rate', 'How the page is doing.'),
                   ('+ Add link / + Header / + Text', 'Add a button, a heading or a line of text.'),
                   ('Each button',
                    'Title, optional image, <b>Spotlight</b> to make it stand out, <b>18+</b> to mark it as adult, '
                    'arrows to reorder.'),
                   ('Social icons', 'Tap a platform and type your username; the link is made for you.')]},
         {'id': 'profile',
          'title': 'Profile',
          'shot': 'bio-profile',
          'rows': [('Profile picture', '<b>Change</b> it, or <b>Use her persona picture</b>.'),
                   ('Name / Bio', 'Shown at the top of the page.')]},
         {'id': 'style',
          'title': 'Style',
          'shot': 'bio-style',
          'rows': [('Theme', 'Soft Peach, Velvet Night, Poster, Noir, Mint and more.'),
                   ('Background', 'Solid, Gradient (two colours) or Photo.'),
                   ('Buttons', 'Style, corners and colours.'),
                   ('Fonts / picture shape', 'Name font, body font and how the picture is cropped.')]},
         {'id': 'embed',
          'title': 'Embed',
          'shot': 'bio-embed',
          'rows': [('Direct chat link', 'Opens straight into a full-page chat with her, labelled as AI.'),
                   ('Chat bubble for a site you own',
                    'Pick position and label, then paste the snippet just before &lt;/body&gt;.')],
          'tips': ['Press <b>Save</b> after every change; the page goes live straight away.']}],
        'tips': [
            'Put your best link first and spotlight it.',
            'Use a safe-work picture; bio platforms review it.',
            'Watch the click rate and move the weakest link down.',
            'The free <a href="/free-link-in-bio">link-in-bio builder</a> works before you sign up.',
        ],
    },
    'wishes': {
        'group': 'Chat & sales',
        'title': 'Fan wishes',
        'early': True,
        'summary': 'When a fan asks for a specific picture, she makes it from her character and sells it as a locked message.',
        'steps': [
            'Open <b>Fan wishes</b> and pick the persona.',
            'Choose <b>Where wishes work</b> and set the safe and explicit prices.',
            'Type a <b>Test phrase</b> to check what counts as a wish, then press <b>Save</b>.',
        ],
        'options': [
            ('Where wishes work', 'The channels that take wishes.'),
            ('Safe price / Explicit price', 'What a fan pays to unlock a wish of each rating.'),
            ('Test phrase', 'Try a message and see whether it counts as a wish.'),
            ('Link provider', 'How web chat and Telegram wishes are paid for.'),
            ('Link test', 'Makes one $3 Fanvue link from her vault and deletes it straight away.'),
        ],
        'tips': [
            'Each wish spends your tokens, so price it above its cost.',
            'A fan\'s next wish waits until the last one is bought.',
            'Requests outside her limits are refused automatically.',
        ],
    },
    'fanvue': {
        'group': 'Platforms', 'title': 'Fanvue', 'guide': 'fanvue',
        'summary': 'She chats with your Fanvue fans and sells PPV ladders.',
        'tips': [
            'Price tier 1 low; it is the door to the rest.',
            'Use <b>Try a message</b> before switching her on.',
            'Slow, believable timing sells better than instant replies.',
        ],
    },
    'telegram': {
        'group': 'Platforms', 'title': 'Telegram', 'guide': 'telegram',
        'summary': 'She chats with fans on Telegram, as a bot or a real account.',
        'tips': [
            'The bot route is the quickest start; the account route feels more personal.',
            'Short follow-ups bring quiet fans back without spamming them.',
        ],
    },
    'x': {
        'group': 'Platforms', 'title': 'X', 'guide': 'x',
        'summary': 'She posts, replies to comments and talks to fans on X.',
        'tips': [
            'Reply to comments under her own posts first; it is the warmest audience.',
            'Keep cold outreach low and personal.',
        ],
    },
    'threads': {
        'group': 'Platforms', 'title': 'Threads', 'guide': 'threads',
        'summary': 'She posts on Threads and answers comments, mentions and DMs.',
        'tips': [
            'Let her write a week of posts, then edit the ones that miss.',
            'Keep Threads safe for work.',
        ],
    },
    'instagram': {
        'group': 'Platforms', 'title': 'Instagram', 'guide': 'instagram',
        'summary': 'Post a feed post, Story or Reel from her vault. Posting only; no DMs.',
        'tips': [
            'Post only safe-work media.',
            'Post at a human pace; a burst of posts looks automated.',
        ],
    },
    'discord': {
        'group': 'Platforms', 'title': 'Discord', 'guide': 'discord',
        'summary': 'She replies in server channels and DMs from a real Discord account.',
        'tips': [
            'Channels never get the paid link; it only goes out in DMs.',
            'Start with a few channels and a low reply rate.',
        ],
    },
    'account': {
        'group': 'Account',
        'title': 'Account & support',
        'summary': 'Your plan, billing, team and how to reach us.',
        'steps': [
            'Open <b>Account</b> for your plan, billing and sign-in details.',
            'Press <b>Upgrade</b> in the top bar to change plan.',
            'Use the <b>support bubble</b> at the bottom of any page to ask a question.',
        ],
        'options': [
            ('Support assistant', 'Answers straight away, day and night.'),
            ('Talk to a person', 'Ask for a person and the team takes over the same chat.'),
            ('Refer a creator', 'Share your link and earn 5% of what they pay.'),
            ('Light / dark', 'Switch the theme from the sidebar.'),
        ],
        'tips': [
            'Include the screen and what you pressed when you ask for help.',
        ],
    },
}

ORDER = list(PAGES)
