"""Creator Help Center: one page per feature, rendered by templates/help.html.

The platform consoles already explain every control in their own setup wizards
(js/*-guide.js). Their help pages render those same steps (`guide`), so the
console and its help page can never disagree; only the tips are written here.
"""

GROUPS = ['Start here', 'Content creation', 'Chat & sales', 'Platforms', 'Account']

PAGES = {
    'getting-started': {
        'group': 'Start here',
        'title': 'Getting started',
        'summary': 'The order to set things up in, from an empty account to a persona earning on a platform.',
        'steps': [
            'Create a <b>character</b> in Character Creator: her face, body and approved photos. Every photo made later is generated from her.',
            'Make photos of her in the <b>Generation Studio</b> and press <b>Keep</b> on the good ones. Kept photos go to the Content Vault.',
            'Create a <b>persona</b> (subscription plans): her voice, backstory and how she moves a fan from hello to a sale.',
            'Open <b>Chat</b> and talk to her yourself until she sounds right.',
            'Connect a <b>platform</b> (Fanvue, Telegram, X, Threads, Instagram, Discord) and switch her on.',
            'Publish your <b>Link in bio</b> page and put it in your social bios.',
        ],
        'options': [
            ('Free plan', 'Characters, the studio, token top-ups and one link-in-bio page. Chatbot features show as <i>Subscribers only</i>.'),
            ('Paid plans', 'Everything on Free, plus personas, chat, the planner and every platform.'),
            ('Search box', 'The dashboard sidebar search finds any screen by keyword, e.g. "ppv" or "schedule".'),
            ('Guide button', 'Most screens have a <b>Guide</b> that walks you through the real controls one step at a time.'),
        ],
        'tips': [
            'Build the character first. A persona linked to an approved character fills in her looks for you.',
            'Nothing a generation makes reaches a fan until you keep it.',
            'Test every change in Chat before a fan sees it.',
        ],
    },
    'plans-and-tokens': {
        'group': 'Start here',
        'title': 'Plans & tokens',
        'summary': 'What each plan includes, how tokens are spent and how to top up.',
        'steps': [
            'Open <b>Tokens</b> in the top bar to see your balance and the price list.',
            'Pick a pack and pay by card or crypto. Tokens land as soon as the payment clears.',
            'Every generate button shows its token price before you click.',
        ],
        'options': [
            ('Free', '15 one-time tokens. Studio, characters, one link-in-bio page.'),
            ('Demo', '25 tokens a month.'),
            ('Starter', '150 tokens a month, personas and chat.'),
            ('Pro', '800 tokens a month.'),
            ('Agency', '2,500 tokens a month.'),
            ('Monthly allowance', 'Arrives at the start of each month and expires at the end of it. It is always spent before tokens you bought.'),
            ('Bought tokens', 'Packs of 100, 500, 1,000, 2,000 and 5,000. They never expire.'),
            ('Refunds', 'A generation that fails returns its tokens to the bucket they came from.'),
        ],
        'tips': [
            'Bigger packs cost less per token.',
            'Generate one photo to test a prompt, then raise <b>How many</b> once it looks right.',
            'Upgrade from <b>Upgrade</b> in the top bar; your bought tokens carry over.',
        ],
    },
    'characters': {
        'group': 'Content creation',
        'title': 'Character Creator',
        'summary': 'Her fixed look. A character drives every photo made for her, so she always looks like herself.',
        'steps': [
            'Press <b>+ New character</b>, or <b>I already have her</b> to use photos you own.',
            '<b>Basics:</b> name, age (18 or over) and explicitness level (SFW, Topless, Explicit).',
            '<b>Her face:</b> build it from drawings, or blend reference photos into a new face. Press <b>Generate face options</b>.',
            'Tap the best option, run the <b>Feature check</b> and press <b>Approve face</b>. Nothing else unlocks until the face is approved.',
            'Optional: add three more face angles for extra control.',
            '<b>Body profile:</b> start from a preset or match reference bodies, then fine-tune under Advanced.',
            'Generate each remaining photo with its own button and approve one per step.',
            'Under <b>Her persona</b>, give her a chatting side, or press <b>Open the studio</b> to create content.',
        ],
        'options': [
            ('Explicitness level', 'The most explicit photo this character may ever have. Safe-work shots never use explicit photos of her.'),
            ('Create with the builder', 'Pick every facial feature from drawings.'),
            ('Blend reference photos', 'The new face takes features from several photos and is none of them. You confirm you have the rights and everyone is 18+.'),
            ('Optional steers', 'Extra hints for the face, e.g. a look or vibe.'),
            ('Options per try', 'How many choices each Generate makes. More choices cost more tokens.'),
            ('Feature check', 'An automatic check that she looks adult and matches the features you picked. Tick all matches to approve.'),
            ('Adjust the crop', 'Drag the box to reframe a photo, then use the crop as the photo or as a reference.'),
            ('Use your own reference photo', 'Steers pose, angle or framing for one photo. Her look still comes from the approved photos.'),
            ('Start from a preset', 'Sets her whole body, breast size and intimate shapes in one click.'),
            ('Advanced', 'Adjust single body features. Each pick overrides the preset.'),
            ('Required vs optional photos', 'Required photos unlock the next step; optional ones add control.'),
            ('Re-approve', 'Approving a new photo saves a new version. Photos that depend on it show as outdated until you redo them.'),
        ],
        'tips': [
            'Spend your effort on the face. Every later photo copies it.',
            'Pick a clear, front-facing, evenly lit face option.',
            'Options you do not approve delete themselves after 3 days.',
            'Characters are unlimited on every plan; only personas count against your plan.',
        ],
    },
    'studio': {
        'group': 'Content creation',
        'title': 'Generation Studio',
        'summary': 'Make photos and clips of her. The price is on the button before you click.',
        'steps': [
            'Pick the <b>Rating</b>: Safe or Explicit.',
            '<b>1 · Engine:</b> choose the model that makes the photo.',
            '<b>2 · Character:</b> choose whose photos these are and where her look comes from.',
            '<b>3 · Prompt:</b> pick the place, what is happening and her expression; the direction fills itself in.',
            '<b>4 · Size & generate:</b> choose size, shape and how many, then press <b>Generate</b>.',
            'Results land unapproved. Press <b>Keep</b> to move a photo into her vault, or <b>Drop</b>. The rest delete themselves after 3 days.',
        ],
        'option_groups': [
            ('Who and where', [
                ('Her look comes from', '<b>Her character</b>, <b>Face & body photos</b>, or <b>Both</b> (character first).'),
                ('Where is she', 'The setting. A picked photo of a place wins over the text; only the place is copied, never people in it.'),
                ('What is happening', 'Explicit only: the act or pose, added on top of the setting. Pick <b>Write your own…</b> to use your words.'),
                ('Content type / Style / Expression / Zoom', 'Shape the shot without writing a prompt.'),
                ('What she\'s doing', 'Follows your choices. Press <b>✦ Suggest</b> for a different idea, or type your own.'),
                ('What she wears', 'Describe it, or pick an outfit photo. This overrides every other outfit; only the clothes are copied.'),
            ]),
            ('Camera & look', [
                ('Phone camera', 'Makes it look shot on a phone.'),
                ('Lighting / Photo quality', 'The light and finish of the photo.'),
                ('Phone look', 'Free grain, soft lens and glow: Off, Light, Medium or Heavy.'),
                ('Smudges and dust', 'Adds marks on the lens or mirror for realism.'),
                ('Advanced', 'See or edit the full prompt. <b>Write the prompt</b> turns your choices into words.'),
                ('Keep out of the shot', 'Things to avoid. A safety baseline is always added.'),
            ]),
            ('Size & generate', [
                ('Size', 'Resolution. Bigger costs more.'),
                ('How many', 'Photos per click.'),
                ('Frame shape', 'Portrait, square or landscape. Same price whichever you pick.'),
            ]),
            ('Photo to Video', [
                ('Photo to animate', 'A clip always starts from a photo you already kept, so the first frame is her.'),
                ('Motion', 'Presets, ideas from the photo, or your own words for the movement.'),
                ('Seconds / Clip size', 'Length and resolution of the clip; both change the price.'),
                ('Sound', 'Keep, generate or upload audio for the clip.'),
            ]),
            ('Kept photos', [
                ('Select / Select all', 'Pick several kept photos for a bulk action.'),
                ('Upload to Fanvue', 'Send selected photos to your Fanvue vault (subscribers only).'),
                ('Undress', 'Open a kept photo in Undress.'),
            ]),
        ],
        'tips': [
            'Set the rating first; it narrows everything else.',
            'Generate one, check it, then raise How many.',
            'Use an outfit photo when the clothes must match exactly.',
            'Keep only your best shots so the vault stays easy to search.',
            'Press <b>Guide</b> at the top for a tour of the real panels.',
        ],
    },
    'undress': {
        'group': 'Content creation',
        'title': 'Undress',
        'early': True,
        'summary': 'Turn a photo of her into an undressed version. Private to your account.',
        'steps': [
            '<b>Add a photo:</b> drop it on the page, or press Undress on a kept photo in the studio.',
            '<b>Click Undress.</b> It takes about a minute; the result appears next to its original.',
            '<b>Download or delete.</b> Select several photos for bulk actions.',
        ],
        'options': [
            ('Show original', 'Compare the result with the photo it came from.'),
            ('Select all / Download / Delete', 'Bulk actions on the selected photos.'),
        ],
        'tips': [
            'Use photos of your own character only.',
            'A clear, well-lit, full-body photo gives the best result.',
        ],
    },
    'vault': {
        'group': 'Content creation',
        'title': 'Content Vault',
        'summary': 'Every approved photo and clip: uploads plus whatever you kept from the studio. The only place sends and posts pick from.',
        'steps': [
            'Open <b>Content Vault</b> from the sidebar.',
            'Upload files, or keep generations in the studio to fill it.',
            'Rate each item <b>Safe for work</b> or <b>Explicit</b>, and sort it into folders.',
        ],
        'options': [
            ('Search', 'Find media by name.'),
            ('Rating filter', 'Safe for work, Explicit or Unrated.'),
            ('Favourites only', 'Show starred items.'),
            ('Sort', 'Newest first or oldest first.'),
            ('Cards / list', 'Switch the layout.'),
            ('Folders', 'Group media; name the folder when you create it.'),
            ('Upload', 'Add your own photos and clips.'),
        ],
        'tips': [
            'Rate everything. Unrated media can land in the wrong place, and safe-work channels only use safe-work media.',
            'Use folders per set or per shoot so pickers stay quick.',
            'Unreviewed generations never appear here, so nothing unchecked reaches a fan.',
        ],
    },
    'personas': {
        'group': 'Chat & sales',
        'title': 'Personas',
        'summary': 'Her chatting side: voice, backstory and how she moves a fan from hello to a sale.',
        'steps': [
            'Press <b>+ New Persona</b> and name her. The setup walks you through four stages, one question at a time.',
            '<b>Who she is:</b> name, age, personality, backstory and looks.',
            '<b>How she talks:</b> writing style, warmth, interests, reply speed and flirt pace.',
            '<b>How she earns:</b> how far she goes and where fans should end up.',
            '<b>Go live:</b> press <b>Test Chat</b>, then <b>Save & Deploy</b>. Nothing is published until you do.',
        ],
        'option_groups': [
            ('Who she is', [
                ('Display name / Age / Gender', 'What every fan sees first. Age must be 18 or over.'),
                ('Location', 'Leave blank and she keeps it vague.'),
                ('Personality archetype', 'Deadpan / Dry, Bubbly / Sweet, Dominant / Edgy, Girl-Next-Door, Mysterious / Dark, Playful / Teasing or Intellectual / Witty.'),
                ('Backstory', 'Two or three sentences: job, city, vibe. <b>Build with AI</b> interviews you and writes it.'),
                ('Appearance', 'Free text that replaces the boxes below it. Linking a character fills these in.'),
                ('Body type / Chest size / Hair / Eyes / Style', 'Her look in words.'),
                ('Her phone', 'Used only in selfies, where it is in shot.'),
                ('Her voice', 'How she sounds when a clip has her speak.'),
                ('Never in her photos', 'Comma-separated things struck out of every generation, e.g. tattoos.'),
            ]),
            ('How she talks', [
                ('Speech style', 'Slang, punctuation and quirks. <b>✨ Generate</b> writes it from her personality.'),
                ('Reply length', 'Short (1–2 sentences), medium or long.'),
                ('Emoji use', 'None, rare, some or lots.'),
                ('Write in lowercase', 'Off gives normal capitalisation.'),
                ('Warmth level', 'Slider from cold (1) to affectionate (5).'),
                ('Question frequency', 'Rarely, sometimes, often or very often.'),
                ('Interests', 'Topics she steers back to, comma-separated.'),
                ('Reply speed', 'Pause before typing on your web chat: instant, fast, natural or slow.'),
                ('Typing speed', 'How long the typing bubble runs: fast, natural or slow.'),
                ('Flirt escalation pace', 'Slow (over many chats), moderate, fast (one chat) or instant.'),
            ]),
            ('How she earns', [
                ('Enable NSFW', 'Lets her go adult. <b>NSFW level</b> sets the ceiling: suggestive, moderate or explicit.'),
                ('Conversion triggers', 'When and how she brings up your offer. Auto-fills on save; edit freely.'),
                ('When a fan asks for spicy content', 'Off, normal, fast (link in the next reply or two) or instant (link in the same reply).'),
                ('Release an explicit preview after', 'After this many asks she attaches a preview photo to the link. 0 turns it off.'),
                ('Funnel phases', 'How long each phase lasts and how often she sends photos. The link goes out in the final phase.'),
                ('CTA destination URL / label', 'Your paid page and the line she says before it.'),
                ('Free-trial URL / label', 'Sent instead to fans who never opened the paid link.'),
                ('Promo code / expires', 'Added after the label until the date passes.'),
                ('A different paid link per channel', 'One per line, so each platform can send its own link.'),
                ('What fans told her to drop', 'Topics fans asked her to stop. She never raises them again; remove an entry to undo.'),
            ]),
        ],
        'tips': [
            'Short replies, little emoji and lowercase read most like a real person.',
            'Slow or natural reply speed feels human; instant feels like a bot.',
            'A slow burn keeps fans chatting for weeks; instant converts faster but burns out sooner.',
            'Write conversion triggers as moments, not sales lines: "when he asks what I did today".',
            'Use <b>Preview Prompt</b> to see exactly what she is told.',
        ],
    },
    'chat': {
        'group': 'Chat & sales',
        'title': 'Chat',
        'summary': 'Talk to your persona exactly as a fan would, before any fan does.',
        'steps': [
            'Open <b>Chat</b> from the sidebar and pick the persona.',
            'Write the way your fans write, including the questions they ask.',
            'Change a setting in the persona builder, save, and chat again to compare.',
        ],
        'options': [
            ('Live Chat / System Prompt / Funnel', 'Tabs in the builder preview: the chat, what she is told, and which funnel stage the chat is in.'),
            ('Funnel stages', 'Warm, Engage, Intrigue, Tease, Offer, Close. Your flirt pace sets how fast she moves.'),
        ],
        'tips': [
            'Try the awkward messages too: rude fans, "are you a bot?", price questions.',
            'If she sells too early, slow the flirt pace or the spicy-content setting.',
        ],
    },
    'planner': {
        'group': 'Chat & sales',
        'title': 'Content Planner',
        'summary': 'Plan a week of posts across your channels in one calendar.',
        'steps': [
            'Press <b>Plan the week</b> for a full week drafted for you, or <b>New post</b> for one.',
            'Pick the <b>Channels</b> and <b>When</b>; add more dates with <b>+ Add date</b>.',
            'Write the post, or press <b>✨ Write it</b>.',
            'Add media from the vault, or press <b>🎨 Create media</b> to make it from the post text.',
            'Press <b>Save changes</b>, or <b>Post now</b>.',
        ],
        'options': [
            ('Same post everywhere', 'One text for every channel instead of one each.'),
            ('Auto / SFW / NSFW', 'The rating of the post. Auto follows the channel.'),
            ('Where it lands on Instagram', 'Feed post, Story or Reel.'),
            ('Send the mass DM to / But not to', 'Fanvue lists who gets the message.'),
            ('Who sees it on Fanvue', 'Followers and subscribers, or subscribers only.'),
            ('Unlock price', 'Empty for a free post. A price needs media; Fanvue\'s minimum is $3.'),
            ('Clear week', 'Remove every planned post this week.'),
        ],
        'tips': [
            'Plan the week on Monday, then only tweak.',
            'Mix free posts with paid ones so followers keep opening them.',
            'Keep safe-work channels safe-work; the planner shows each post\'s rating.',
        ],
    },
    'link-in-bio': {
        'group': 'Chat & sales',
        'title': 'Link in bio',
        'summary': 'One page for your social bios with all your links, on a neutral domain.',
        'steps': [
            'Open <b>Link in bio</b> from the sidebar.',
            '<b>Links:</b> add links, headers, text and a <b>Chat with me</b> button.',
            '<b>Profile:</b> picture, name and bio.',
            '<b>Style:</b> theme, background, buttons and fonts.',
            'Press <b>Save</b>, then <b>Copy link</b> and paste it into your Instagram, TikTok or X bio.',
        ],
        'options': [
            ('Social icons', 'Tap a platform and type your username; the link is made for you.'),
            ('18+ content', 'Marks the page as adult.'),
            ('Use her persona picture', 'Reuse her profile picture, or pick an approved safe-work photo.'),
            ('Theme / Background', 'One or two colours, or a photo.'),
            ('Buttons', 'Corners, button colour, text colour and spotlight.'),
            ('Name font / Body font / Picture shape', 'Text and picture styling.'),
            ('Page views / Button clicks / Click rate', 'How the page is performing.'),
            ('Direct chat link', 'Opens straight into a full-page chat with her, labelled as AI.'),
            ('Chat bubble for a site you own', 'Paste the snippet before &lt;/body&gt;; choose position and label.'),
        ],
        'tips': [
            'Put your best link first and spotlight it.',
            'Use a safe-work picture; bio platforms review it.',
            'Watch the click rate and move the weakest link down.',
            'The free <a href="/free-link-in-bio">link-in-bio builder</a> works before you sign up.',
        ],
    },
    'wishes': {
        'group': 'Chat & sales',
        'title': 'Fan wishes',
        'early': True,
        'summary': 'When a fan asks for a specific picture, she makes it from her character and sells it as a locked message.',
        'steps': [
            'Open <b>Fan wishes</b> and pick the persona.',
            'Choose <b>Where wishes work</b> and set the safe and explicit prices.',
            'Type a <b>Test phrase</b> to check what counts as a wish, then press <b>Save</b>.',
        ],
        'options': [
            ('Where wishes work', 'The channels that take wishes.'),
            ('Safe price / Explicit price', 'What a fan pays to unlock a wish of each rating.'),
            ('Test phrase', 'Try a message and see whether it counts as a wish.'),
            ('Link provider', 'How web chat and Telegram wishes are paid for.'),
            ('Link test', 'Makes one $3 Fanvue link from her vault and deletes it straight away.'),
        ],
        'tips': [
            'Each wish spends your tokens, so price it above its cost.',
            'A fan\'s next wish waits until the last one is bought.',
            'Requests outside her limits are refused automatically.',
        ],
    },
    'fanvue': {
        'group': 'Platforms', 'title': 'Fanvue', 'guide': 'fanvue',
        'summary': 'She chats with your Fanvue fans and sells PPV ladders.',
        'tips': [
            'Price tier 1 low; it is the door to the rest.',
            'Use <b>Try a message</b> before switching her on.',
            'Slow, believable timing sells better than instant replies.',
        ],
    },
    'telegram': {
        'group': 'Platforms', 'title': 'Telegram', 'guide': 'telegram',
        'summary': 'She chats with fans on Telegram, as a bot or a real account.',
        'tips': [
            'The bot route is the quickest start; the account route feels more personal.',
            'Short follow-ups bring quiet fans back without spamming them.',
        ],
    },
    'x': {
        'group': 'Platforms', 'title': 'X', 'guide': 'x',
        'summary': 'She posts, replies to comments and talks to fans on X.',
        'tips': [
            'Reply to comments under her own posts first; it is the warmest audience.',
            'Keep cold outreach low and personal.',
        ],
    },
    'threads': {
        'group': 'Platforms', 'title': 'Threads', 'guide': 'threads',
        'summary': 'She posts on Threads and answers comments, mentions and DMs.',
        'tips': [
            'Let her write a week of posts, then edit the ones that miss.',
            'Keep Threads safe for work.',
        ],
    },
    'instagram': {
        'group': 'Platforms', 'title': 'Instagram', 'guide': 'instagram',
        'summary': 'Post a feed post, Story or Reel from her vault. Posting only; no DMs.',
        'tips': [
            'Post only safe-work media.',
            'Post at a human pace; a burst of posts looks automated.',
        ],
    },
    'discord': {
        'group': 'Platforms', 'title': 'Discord', 'guide': 'discord',
        'summary': 'She replies in server channels and DMs from a real Discord account.',
        'tips': [
            'Channels never get the paid link; it only goes out in DMs.',
            'Start with a few channels and a low reply rate.',
        ],
    },
    'account': {
        'group': 'Account',
        'title': 'Account & support',
        'summary': 'Your plan, billing, team and how to reach us.',
        'steps': [
            'Open <b>Account</b> for your plan, billing and sign-in details.',
            'Press <b>Upgrade</b> in the top bar to change plan.',
            'Use the <b>support bubble</b> at the bottom of any page to ask a question.',
        ],
        'options': [
            ('Support assistant', 'Answers straight away, day and night.'),
            ('Talk to a person', 'Ask for a person and the team takes over the same chat.'),
            ('Refer a creator', 'Share your link and earn 5% of what they pay.'),
            ('Light / dark', 'Switch the theme from the sidebar.'),
        ],
        'tips': [
            'Include the screen and what you pressed when you ask for help.',
        ],
    },
}

ORDER = list(PAGES)
