"""Public marketing pages, one per platform, rendered from templates/platform.html.

Separate from the signed-in consoles at /telegram and /fanvue: these are the SEO
landing pages a stranger arrives on, so the slugs carry the keyword rather than
the platform name on its own.
"""

import json


def _faq_schema(faq):
    return json.dumps({
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        'mainEntity': [{'@type': 'Question', 'name': f['q'],
                        'acceptedAnswer': {'@type': 'Answer', 'text': f['a']}}
                       for f in faq],
    })


# Every page carries the same set of sibling links, minus itself.
_ALL = [
    {'slug': 'telegram-ai-chatbot', 'name': 'Telegram', 'tag': 'Private fan DMs with the full funnel', 'status': 'Live'},
    {'slug': 'fanvue-ai-chatter', 'name': 'Fanvue', 'tag': 'The paid page your funnel lands on', 'status': 'Live'},
    {'slug': 'discord-ai-chatbot', 'name': 'Discord', 'tag': 'DM conversations, clean servers', 'status': 'Live'},
    {'slug': 'x-ai-bot', 'name': 'X (Twitter)', 'tag': 'Posts, replies and a DM funnel', 'status': 'Live'},
    {'slug': 'instagram-posting-automation', 'name': 'Instagram', 'tag': 'Posts, Stories and Reels on schedule', 'status': 'Live'},
    {'slug': 'threads-auto-reply', 'name': 'Threads', 'tag': 'Posting and comment auto-reply', 'status': 'Live'},
    {'slug': 'velvetchat-share-link', 'name': 'Velvetchat', 'tag': 'Your own chat page and embed', 'status': 'Live'},
    {'slug': 'ai-content-planner', 'name': 'Content Planner', 'tag': 'A month of posts in one calendar', 'status': 'Live'},
    {'slug': 'ai-image-generator', 'name': 'Generation Studio', 'tag': 'Photos and clips of your persona', 'status': 'Soon'},
    {'slug': 'onlyfans-ai-chatbot', 'name': 'OnlyFans', 'tag': 'Inbox auto-reply and PPV', 'status': 'Soon'},
    {'slug': 'fansly-ai-chatbot', 'name': 'Fansly', 'tag': 'Another paid page to funnel into', 'status': 'Soon'},
    {'slug': 'reddit-posting-bot', 'name': 'Reddit', 'tag': 'Per-subreddit posting and comments', 'status': 'Soon'},
    {'slug': 'tiktok-posting-automation', 'name': 'TikTok', 'tag': 'Safe-for-work clips on schedule', 'status': 'Soon'},
]


def _related(slug, picks):
    by_slug = {p['slug']: p for p in _ALL}
    return [{'href': '/' + s, 'name': by_slug[s]['name'], 'tag': by_slug[s]['tag'],
             'status': by_slug[s]['status']} for s in picks if s != slug]


PAGES = {
    'telegram-ai-chatbot': {
        'slug': 'telegram-ai-chatbot',
        'live': True,
        'title': 'Telegram AI Chatbot for Creators | Velvetfunnel',
        'description': ('Give every persona her own Telegram bot. Automated fan DMs, memory, photo '
                        'teasing and a built-in conversion funnel that sells your paid page 24/7.'),
        'eyebrow': 'Live now · DM funnel',
        'h1_pre': 'Telegram AI chatbot for',
        'h1_accent': 'fan DMs.',
        'lede': [
            'Every persona gets her own Telegram bot, so fans message her directly in a private one '
            'to one chat. Telegram is the strongest converting channel in the stack because the '
            'conversation is private, uninterrupted and yours.',
            'The full funnel runs here. She warms fans up, remembers past chats, attaches a preview '
            'photo when a fan asks to see more, and sends your paid link once the fan is ready.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Live in minutes. Create the bot with BotFather, paste the token, and she is running.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'A fan finds you', 'detail': 'From your X, Instagram or Threads bio, through a tracked link.'},
            {'label': 'She opens the chat', 'detail': 'Your persona answers in her own voice, in a private Telegram DM.'},
            {'label': 'The funnel runs', 'detail': 'Warm, engage, intrigue, tease, offer, close, at the pace you set.'},
            {'label': 'They land on your paid page', 'detail': 'The CTA goes out in character, with a preview photo attached when it earns one.'},
        ],
        'route_foot': 'Destination: <b>your Fanvue page</b>. OnlyFans and Fansly are next.',
        'features_eyebrow': 'What she does',
        'features_h2_pre': 'A real inbox, worked',
        'features_h2_accent': 'around the clock',
        'features_sub': ('Everything below runs server side on every account you own. No open tab, no '
                         'browser, no chatter sitting in a shift.'),
        'features': [
            {'icon': '💬', 'title': 'Replies in your voice',
             'body': 'Sentence length, punctuation, emoji use and typing speed are all set by you in the persona builder. Telegram paces its own replies, so she never reads like a bot.'},
            {'icon': '🧠', 'title': 'Remembers every fan',
             'body': 'She brings back what a fan told her last week and picks the thread up where it stopped. No conversation ever restarts from zero.'},
            {'icon': '📸', 'title': 'Photo-backed offers',
             'body': 'Once a fan has asked to see more enough times to mean it, the CTA goes out with a preview photo from your library attached, not a bare link.'},
            {'icon': '🎯', 'title': 'Handles the objection',
             'body': 'A fan who was sent the paid link and never opened it is hesitating. She sends a free trial or a discount code next time instead of repeating the same ask.'},
            {'icon': '⏰', 'title': 'Wins quiet fans back',
             'body': 'When a fan stops replying she returns on day 1, 4, 12 and 30, then quarterly. The first messages are plain conversation, the link only comes later.'},
            {'icon': '📊', 'title': 'Logs and scores everything',
             'body': 'Every conversation is logged with its funnel stage, so you can see who is warming up and which channel actually sent them.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'No servers, no code, no browser left open on a machine somewhere.',
        'steps': [
            {'title': 'Build the persona', 'body': 'Fill in her identity, voice and funnel pacing in the visual builder. Or describe her in a sentence and let the AI draft it for you to edit.'},
            {'title': 'Create the bot', 'body': 'Open BotFather in Telegram, send /newbot, and paste the token into Velvetfunnel. That is the whole connection.'},
            {'title': 'Send traffic', 'body': 'Put your tracked Telegram link in the bios she already posts to. Every fan who opens it is credited to the channel that found them.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Telegram against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Each platform does a different job. Telegram is where the conversation gets private enough to close.',
        'rows': [
            {'k': 'Telegram', 'v': 'Private DM, no algorithm between you and the fan, no posting requirement. The strongest converting channel in the stack.'},
            {'k': 'Discord', 'v': 'Also a DM funnel, but public server channels stay clean: no funnel, no links, no CTA, ever.'},
            {'k': 'X (Twitter)', 'v': 'Public posts and replies that build reach, plus a DM funnel that converts it. The one channel that does both.'},
            {'k': 'Instagram and Threads', 'v': 'Reach only. They fill the funnel and hand fans to Telegram through a tracked bio link.'},
            {'k': 'Fanvue', 'v': 'The destination. Once a fan subscribes, the same persona keeps working inside that inbox and sells PPV from your vault.'},
        ],
        'faq': [
            {'q': 'Will fans know they are talking to an AI?',
             'a': 'That is your call and your setting. The persona is built to stay in character, and every chat Velvetfunnel hosts on your own page is labelled as an AI chat. On Telegram the bot is your bot, so you decide what its description says.'},
            {'q': 'Do I need to keep a browser or a tab open?',
             'a': 'No. The Telegram loop runs server side and stays on through deploys. Your machine can be off.'},
            {'q': 'Can I run more than one persona?',
             'a': 'Yes. Each persona gets her own bot and her own token, and they run at the same time without sharing memory or settings.'},
            {'q': 'What stops her sending the offer too early?',
             'a': 'The funnel is phased. You set how long each phase lasts and how often she sends photos, and the paid link only fires once a fan reaches the final phase.'},
            {'q': 'Does she repeat herself over a long conversation?',
             'a': 'No. Every message she sends is logged and fed back as context, and when a fan tells her to drop a subject she writes it down and never raises it again, with him or with anyone, on any platform.'},
            {'q': 'Where does the paid link point?',
             'a': 'Your Fanvue page today, with OnlyFans and Fansly landing next. You can also point a channel at your own Velvetchat page instead, and change the destination later without touching a single bio.'},
        ],
        'related': _related('telegram-ai-chatbot', ['fanvue-ai-chatter', 'discord-ai-chatbot', 'x-ai-bot', 'velvetchat-share-link']),
        'close_h2': 'Put her on Telegram tonight',
        'close_sub': 'Build the persona once and she works the inbox from then on, in your voice, on every account you own.',
    },

    'fanvue-ai-chatter': {
        'slug': 'fanvue-ai-chatter',
        'live': True,
        'title': 'Fanvue AI Chatter & PPV Automation | Velvetfunnel',
        'description': ('Fanvue is where your funnel lands. An AI chatter works your subscriber inbox, '
                        'sells PPV from your vault and keeps every paying fan engaged 24/7.'),
        'eyebrow': 'Live now · Paid destination',
        'h1_pre': 'Fanvue AI chatter and',
        'h1_accent': 'PPV automation.',
        'lede': [
            'Fanvue is the paid page every other channel points at. Your social platforms build the '
            'audience, the DM funnel warms them up, and Fanvue is where they subscribe.',
            'Velvetfunnel does not stop at the paywall. The same persona keeps working inside your '
            'Fanvue inbox, reading incoming messages and replying in character, so a fan who just '
            'paid gets the same voice they were talking to an hour ago.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Runs server side, through deploys, with no open tab and no browser running.',
        'route_title': 'Where Fanvue sits',
        'route': [
            {'label': 'Traffic arrives', 'detail': 'Telegram, Discord, X, Instagram and Threads build the audience.'},
            {'label': 'The funnel warms them', 'detail': 'Your persona works the DM until the fan is ready to pay.'},
            {'label': 'They subscribe on Fanvue', 'detail': 'The CTA lands them on your page, credited to the channel that found them.'},
            {'label': 'PPV starts earning', 'detail': 'The same persona works the subscriber inbox and sells from your vault.'},
        ],
        'route_foot': 'Subscription is the floor. <b>PPV is where the margin is.</b>',
        'features_eyebrow': 'Inside the inbox',
        'features_h2_pre': 'The part a human chatter',
        'features_h2_accent': 'is too expensive to work',
        'features_sub': ('Subscription revenue arrives on its own. Everything after it depends on somebody '
                         'answering fast, in character, at three in the morning.'),
        'features': [
            {'icon': '🗄️', 'title': 'Sells from your vault',
             'body': 'Connect your Fanvue vault and she attaches real content to the offer. Browse folders, pick media, send PPV, all from the same dashboard.'},
            {'icon': '🔁', 'title': 'Never sends the same thing twice',
             'body': 'Every PPV drop is tracked per fan, so nothing goes out to somebody who already bought it.'},
            {'icon': '🎚️', 'title': 'Her own pacing',
             'body': 'Fanvue paces its replies independently of your other channels, so she reads right for people who already subscribe rather than for strangers.'},
            {'icon': '⭐', 'title': 'Fan scoring',
             'body': 'Every subscriber is scored by engagement, so you know who is close to the next buy before you spend a message on them.'},
            {'icon': '📈', 'title': 'Funnel and PPV analytics',
             'body': 'See which stage each fan sits in, which conversations are warming toward a drop, and what every drop earned.'},
            {'icon': '🛰️', 'title': 'One worker per account',
             'body': 'Busy accounts each get their own worker, so one full inbox never holds up another. It stays on through redeploys.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'Approve once, and the inbox is worked from then on.',
        'steps': [
            {'title': 'Connect Fanvue', 'body': 'Approve the connection from the Fanvue console in your dashboard. She can then read her inbox and send as herself.'},
            {'title': 'Point your vault at it', 'body': 'Pick the folders she is allowed to sell from, and the price bands she can offer them at.'},
            {'title': 'Turn auto-reply on', 'body': 'Switch it on per persona. From that moment the inbox is answered around the clock, with every conversation logged.'},
        ],
        'rows_eyebrow': 'The destination',
        'rows_h2_pre': 'Where your funnel',
        'rows_h2_accent': 'can land',
        'rows_sub': 'The funnel is built to land anywhere. Fanvue is the paid page supported end to end today.',
        'rows': [
            {'k': 'Fanvue', 'v': 'Live. Subscriber inbox auto-reply, PPV from your vault, fan scoring and funnel analytics.'},
            {'k': 'OnlyFans', 'v': 'In production. Auto-reply and PPV delivery running the same funnel and the same persona. The console and reply loop are built and waiting on release.'},
            {'k': 'Fansly', 'v': 'In production. Next after OnlyFans, so creators who earn there point the same funnel at the same page instead of maintaining two setups.'},
            {'k': 'Velvetchat', 'v': 'Live. Your own chat page on property you control, for channels where a paysite link would get filtered.'},
            {'k': 'Per persona routing', 'v': 'You choose which paid page each persona sends fans to, and change it later without touching a single bio.'},
        ],
        'faq': [
            {'q': 'Does this replace my chatters?',
             'a': 'It covers the volume they cannot: instant replies, overnight, on every conversation at once. Plenty of creators run it alongside a human who steps in on the biggest spenders.'},
            {'q': 'Can it send PPV on its own?',
             'a': 'Yes, from the vault folders you allow, at the price bands you set. Every send is logged and nothing is sent twice to the same fan.'},
            {'q': 'What happens if Fanvue is slow or the connection drops?',
             'a': 'A network failure is treated as a blip and the connection is kept. Only a refusal Fanvue calls final clears the session, because losing it means approving again for nothing.'},
            {'q': 'Does the persona change after a fan pays?',
             'a': 'No, and that is the point. The voice a fan subscribed to is the voice waiting for them inside, with the same memory of what they already talked about.'},
            {'q': 'Do I need to keep a tab open?',
             'a': 'No. It runs server side and stays on through deploys.'},
            {'q': 'Will OnlyFans and Fansly work the same way?',
             'a': 'Yes. Same funnel, same persona, same vault logic, with the destination picked per persona. Both are built and finishing their access work.'},
        ],
        'related': _related('fanvue-ai-chatter', ['telegram-ai-chatbot', 'discord-ai-chatbot', 'x-ai-bot', 'velvetchat-share-link']),
        'close_h2': 'Stop losing PPV to a slow reply',
        'close_sub': 'Your subscribers are already inside. The difference is whether somebody answers them in ten seconds or ten hours.',
    },

    'discord-ai-chatbot': {
        'slug': 'discord-ai-chatbot',
        'live': True,
        'title': 'Discord AI Chatbot for Creators | Velvetfunnel',
        'description': ('Run your persona as a real Discord account. Automated fan DMs with the full '
                        'funnel, natural chime-ins in public channels, and no spam in anyone server.'),
        'eyebrow': 'Live now · DM funnel',
        'h1_pre': 'Discord AI chatbot for',
        'h1_accent': 'fan DMs.',
        'lede': [
            'Your persona runs on Discord as her own account, not as a bot application with a tag '
            'next to her name. Fans DM her the way they DM anyone else, and she answers in her own '
            'voice around the clock.',
            'The full funnel runs in DMs. In public server channels she does the opposite: she '
            'chimes in on the conversation and nothing else, with no funnel, no nudge and no link.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Sign in as her once in a hosted browser. No token pasting, no bot application to register.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'She is already in the servers', 'detail': 'Her own account, her own communities. Velvetfunnel never joins one for her.'},
            {'label': 'She talks in the channels', 'detail': 'Chime-ins that read like a member, on the channels you pick.'},
            {'label': 'A fan opens a DM', 'detail': 'She never messages first. When a fan starts the chat, the funnel starts with it.'},
            {'label': 'The offer lands in the DM', 'detail': 'Warm, engage, intrigue, tease, offer, close, at the pace you set in the builder.'},
        ],
        'route_foot': 'A paid link only ever goes out in a DM. <b>Never in a server channel.</b>',
        'features_eyebrow': 'What she does',
        'features_h2_pre': 'A member of the server,',
        'features_h2_accent': 'not an ad in it',
        'features_sub': ('Discord communities eject promo accounts fast. Everything here is built so she '
                         'reads like somebody who belongs there.'),
        'features': [
            {'icon': '💬', 'title': 'Full funnel in DMs',
             'body': 'Private chats run the same six-stage funnel as Telegram, with the same memory and the same voice from the builder.'},
            {'icon': '🏠', 'title': 'Clean public channels',
             'body': 'Channel replies sit outside the funnel entirely. No offer, no nudge, no CTA, no paid link, by design rather than by setting.'},
            {'icon': '🙋', 'title': 'Never messages first',
             'body': 'She does not open DMs and she does not join servers. A conversation exists because a fan started it.'},
            {'icon': '🧠', 'title': 'Remembers every fan',
             'body': 'What a fan told her last month comes back in the next chat, and a subject he asked her to drop is dropped everywhere.'},
            {'icon': '🛰️', 'title': 'One connection per account',
             'body': 'One socket, one stable client fingerprint, no reconnect loop at a refused token. She looks like the same device every time.'},
            {'icon': '📊', 'title': 'Logged and scored',
             'body': 'Every DM is logged with its funnel stage, so you can see who is warming and which channel sent them.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'No bot application, no developer portal, no token to keep somewhere safe.',
        'steps': [
            {'title': 'Build the persona', 'body': 'Set her identity, voice and funnel pacing in the visual builder, or describe her in a sentence and edit the draft.'},
            {'title': 'Sign in as her', 'body': 'A hosted browser opens Discord\'s own sign-in page, so the captcha, the 2FA and the new-device code are handled by Discord.'},
            {'title': 'Pick her channels', 'body': 'Choose which servers and channels she chimes in on. DMs are on from that moment.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Discord against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Discord is a community channel that happens to have the best private inbox on the internet attached to it.',
        'rows': [
            {'k': 'Discord', 'v': 'Public presence in servers she already belongs to, plus a private DM funnel that converts it.'},
            {'k': 'Telegram', 'v': 'Pure DM. No public side at all, and the strongest converting channel in the stack.'},
            {'k': 'X (Twitter)', 'v': 'Public posts and replies plus a DM funnel, and the only channel that goes looking for new people.'},
            {'k': 'Instagram and Threads', 'v': 'Reach only. They fill the funnel and hand fans over through a tracked bio link.'},
            {'k': 'Fanvue', 'v': 'The destination. Once a fan subscribes, the same persona works that inbox and sells PPV from your vault.'},
        ],
        'faq': [
            {'q': 'Is she a bot application with a BOT tag?',
             'a': 'No. She is connected as her own signed-in account, so fans see a normal Discord user. That also means she can talk in servers she is a member of rather than only ones you can add an app to.'},
            {'q': 'Will she spam servers I care about?',
             'a': 'She cannot. Channel replies run outside the funnel with no offer, no nudge and no link, and that is how the code is written rather than a switch you can flip.'},
            {'q': 'Does she DM people who have not messaged her?',
             'a': 'No. She never opens a DM first. Cold DMs are the fastest way to lose a Discord account, so the path does not exist.'},
            {'q': 'Can she join servers for me?',
             'a': 'No, and she will not try. She talks where her account is already a member.'},
            {'q': 'Do I need to keep a browser open?',
             'a': 'No. The gateway runs server side and stays on through deploys.'},
            {'q': 'Where does the paid link point?',
             'a': 'Your Fanvue page today, with OnlyFans and Fansly landing next. You can also point her at your own Velvetchat page instead.'},
        ],
        'related': _related('discord-ai-chatbot', ['telegram-ai-chatbot', 'fanvue-ai-chatter', 'x-ai-bot', 'velvetchat-share-link']),
        'close_h2': 'Put her in the servers she already lives in',
        'close_sub': 'Community presence in public, a working funnel in private, and nothing that gets her thrown out of either.',
    },

    'x-ai-bot': {
        'slug': 'x-ai-bot',
        'live': True,
        'title': 'X (Twitter) AI Bot for Creators | Auto DM & Reply | Velvetfunnel',
        'description': ('Automate X posts, comment replies and DM conversations with your AI persona. '
                        'Find new leads, start chats and funnel them to your paid page 24/7.'),
        'eyebrow': 'Live now · Reach and DMs',
        'h1_pre': 'X (Twitter) AI bot for',
        'h1_accent': 'posts, replies and DMs.',
        'lede': [
            'Your persona posts to X, replies to comments on her own posts, follows and unfollows, '
            'and runs a complete DM funnel. She can find new people worth talking to, open the '
            'conversation and carry it through to the offer.',
            'X is the one channel in Velvetfunnel that does both jobs at once: public engagement '
            'that builds reach, and private DMs that convert it. Everything runs server side, so it '
            'keeps working with the tab closed.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Posts, replies, DMs and follows all run from one console, on every account you own.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'She posts', 'detail': 'Written by her, scheduled from the content planner or sent straight from the console.'},
            {'label': 'She works the replies', 'detail': 'Comments on her own posts get answered in character, which is what keeps the post alive.'},
            {'label': 'She opens the DM', 'detail': 'Lead gathering finds new accounts worth talking to and sends the first message.'},
            {'label': 'The funnel runs', 'detail': 'Warm, engage, intrigue, tease, offer, close, at the pace you set.'},
        ],
        'route_foot': 'Reach and conversion on one account. <b>Destination: your paid page.</b>',
        'features_eyebrow': 'What she does',
        'features_h2_pre': 'The only channel that',
        'features_h2_accent': 'finds fans and closes them',
        'features_sub': ('Every other platform either builds an audience or converts one. X does both, from '
                         'the same account and the same persona.'),
        'features': [
            {'icon': '📝', 'title': 'Posts in her voice',
             'body': 'Write and send from the console, or plan a week of posts in the content planner and let them fire at their slots.'},
            {'icon': '💬', 'title': 'Replies to her comments',
             'body': 'Comments on her own posts get an in-character answer, which is what keeps a post in front of people.'},
            {'icon': '🧲', 'title': 'Gathers new chats',
             'body': 'Lead gathering finds accounts worth talking to, opens the first message and hands them into the same funnel your other channels use.'},
            {'icon': '🔁', 'title': 'Auto-chat',
             'body': 'Existing DM conversations stay alive without you touching the inbox, one round at a time, at a human pace.'},
            {'icon': '👋', 'title': 'Follow and unfollow',
             'body': 'Run the follow loop from the same console, so growth work and conversation work are not two different tools.'},
            {'icon': '🛰️', 'title': 'Always on',
             'body': 'The whole loop runs server side and stays on through deploys. Your machine can be off.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'One console for posting, replying, DMing and following.',
        'steps': [
            {'title': 'Build the persona', 'body': 'Her identity, voice and funnel pacing come from the visual builder and are shared with every other channel.'},
            {'title': 'Connect the account', 'body': 'Connect her X account from the dashboard. Posting, replies and DMs all run off the same connection.'},
            {'title': 'Turn the loops on', 'body': 'Auto-reply, auto-chat and lead gathering are separate switches, so you can start with reach and add DMs later.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'X against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Most channels do one half of the job. This one does both halves badly enough alone and very well alongside Telegram.',
        'rows': [
            {'k': 'X (Twitter)', 'v': 'Posts, comment replies, DM funnel, lead gathering and follows. The only channel that goes looking for new fans.'},
            {'k': 'Telegram', 'v': 'Where an X conversation is best finished. Private, uninterrupted, no character limit and no algorithm.'},
            {'k': 'Threads', 'v': 'Public only, no DMs. Posting and comment auto-reply, which makes it pure reach.'},
            {'k': 'Instagram', 'v': 'Posting only. Feed posts, Stories and Reels on a schedule, with the funnel handled elsewhere.'},
            {'k': 'Fanvue', 'v': 'The destination. The same persona works that inbox once a fan has paid.'},
        ],
        'faq': [
            {'q': 'Does she post and DM from the same account?',
             'a': 'Yes. One connection covers posting, comment replies, DMs, auto-chat and the follow loop.'},
            {'q': 'What is lead gathering?',
             'a': 'She finds accounts worth talking to, opens the first message and hands that conversation into the same funnel every other channel uses. You set how many she opens.'},
            {'q': 'Will she reply to everything?',
             'a': 'Only what you switch on. Comment replies, auto-chat and lead gathering are three separate switches.'},
            {'q': 'Do I need a browser tab open?',
             'a': 'No. It runs server side and stays on through deploys.'},
            {'q': 'Can the content planner post to X?',
             'a': 'Yes. X is one of the channels the planner publishes to automatically, so a week of posts can be written and scheduled in one sitting.'},
            {'q': 'Where does the paid link point?',
             'a': 'Your Fanvue page today, with OnlyFans and Fansly next. You can also point a channel at your own Velvetchat page, which matters where a paysite link gets filtered.'},
        ],
        'related': _related('x-ai-bot', ['telegram-ai-chatbot', 'threads-auto-reply', 'ai-content-planner', 'fanvue-ai-chatter']),
        'close_h2': 'Reach and conversion on one account',
        'close_sub': 'She posts, she replies, she opens the DM and she closes it, on every account you own, without a tab open.',
    },

    'instagram-posting-automation': {
        'slug': 'instagram-posting-automation',
        'live': True,
        'title': 'Instagram Posting Automation for Creators | Velvetfunnel',
        'description': ('Schedule Instagram feed posts, Stories and Reels from one calendar. Post as a '
                        'real account, plan a week in one sitting, and send the traffic to your funnel.'),
        'eyebrow': 'Live now · Reach',
        'h1_pre': 'Instagram posting automation for',
        'h1_accent': 'Posts, Stories and Reels.',
        'lede': [
            'Instagram is a reach channel and Velvetfunnel treats it as one. Your persona posts to '
            'the feed, to Stories and to Reels, on a schedule you set in the content planner, from '
            'the account your fans already follow.',
            'There is no DM automation and no funnel here on purpose. Instagram fills the funnel and '
            'hands fans over through your bio link. The conversation happens on Telegram, Discord or X.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'A real signed-in account, not a Business API app. Stories work, which the official API cannot do.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'You plan the week', 'detail': 'Posts, Stories and Reels laid out on one calendar, per persona.'},
            {'label': 'She posts them', 'detail': 'Each post fires at its slot from her own account, with the media attached.'},
            {'label': 'Fans follow the bio link', 'detail': 'A tracked link that credits Instagram for every fan it sends.'},
            {'label': 'The funnel takes over', 'detail': 'Telegram, Discord or X runs the DM funnel and ends on your paid page.'},
        ],
        'route_foot': 'Instagram brings them in. <b>Another channel closes them.</b>',
        'features_eyebrow': 'What it does',
        'features_h2_pre': 'A posting channel,',
        'features_h2_accent': 'done properly',
        'features_sub': ('Three formats, one calendar, one account, and none of the Business API paperwork '
                         'that still cannot post a Story.'),
        'features': [
            {'icon': '🖼️', 'title': 'Feed posts, Stories and Reels',
             'body': 'Pick which of the three a planned post lands as. The same caption and media can go out as any of them.'},
            {'icon': '🗓️', 'title': 'Planned a week at a time',
             'body': 'Instagram sits on the same calendar as every other channel, so a week of content is one sitting rather than five.'},
            {'icon': '✍️', 'title': 'Captions in her voice',
             'body': 'Let the persona write the caption, then edit it. The voice is the one from the builder, not a generic content tool.'},
            {'icon': '🔗', 'title': 'Tracked bio link',
             'body': 'Every fan who arrives from Instagram is credited to it, so you can see which channel actually sends buyers.'},
            {'icon': '🔐', 'title': 'Signed in as her',
             'body': 'A hosted browser runs Instagram\'s own sign-in, so the checkpoint, the 2FA and the new-device code are handled by Instagram.'},
            {'icon': '🚫', 'title': 'No DMs, deliberately',
             'body': 'Instagram is the fastest place to lose an account to automated messaging, so there is no DM path here at all.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'No app review, no Business account requirement, no Meta developer portal.',
        'steps': [
            {'title': 'Sign in as her', 'body': 'Approve the connection once in the hosted sign-in browser. Instagram handles its own checks.'},
            {'title': 'Plan the week', 'body': 'Add posts to the calendar, choose feed, Story or Reel for each, and attach the media.'},
            {'title': 'Point the bio at your funnel', 'body': 'Put the tracked link in her bio. Every fan it sends is credited to Instagram.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Instagram against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Reach channels and conversation channels do different jobs. Asking one to do the other is how accounts get lost.',
        'rows': [
            {'k': 'Instagram', 'v': 'Posting only. Feed, Stories and Reels on a schedule. No DMs, no funnel, no comment replies.'},
            {'k': 'Threads', 'v': 'Also public only, but it does reply to comments and mentions on her own posts.'},
            {'k': 'X (Twitter)', 'v': 'Posts and replies plus a full DM funnel, and the only channel that opens conversations.'},
            {'k': 'Telegram and Discord', 'v': 'Where an Instagram follower becomes a conversation, and a conversation becomes a subscriber.'},
            {'k': 'Fanvue', 'v': 'The destination. The same persona keeps selling inside that inbox after the fan pays.'},
        ],
        'faq': [
            {'q': 'Can it reply to DMs or comments?',
             'a': 'No. Instagram is posting only in Velvetfunnel. Automated messaging is what gets creator accounts restricted there, so the path is not built.'},
            {'q': 'Can it post Stories?',
             'a': 'Yes, along with feed posts and Reels. That is one of the reasons it runs as a signed-in account rather than through the official API, which cannot post Stories at all.'},
            {'q': 'Do I need a Business or Creator account?',
             'a': 'No, and no app review either. She signs in as herself.'},
            {'q': 'Can I schedule a week at once?',
             'a': 'Yes. Instagram sits on the same content planner calendar as X, Threads and Fanvue, and you pick feed, Story or Reel per post.'},
            {'q': 'How do fans get from Instagram into the funnel?',
             'a': 'Through a tracked link in her bio. It credits Instagram for every fan it sends, and you can change where it points without editing the bio again.'},
            {'q': 'Is the account at risk?',
             'a': 'Instagram\'s terms do not allow an automated client, so treat it as an account you can afford to lose rather than her only one. Everything here is built to look like ordinary use, and there is no messaging at all.'},
        ],
        'related': _related('instagram-posting-automation', ['threads-auto-reply', 'x-ai-bot', 'ai-content-planner', 'telegram-ai-chatbot']),
        'close_h2': 'Plan a month of Instagram in one sitting',
        'close_sub': 'Feed posts, Stories and Reels on one calendar, in her voice, pointing at a funnel that actually closes.',
    },

    'threads-auto-reply': {
        'slug': 'threads-auto-reply',
        'live': True,
        'title': 'Threads Auto-Reply Bot for Creators | Velvetfunnel',
        'description': ('Post to Threads and reply to every comment and mention in your persona\'s voice. '
                        'Public reach on autopilot, feeding the DM funnel that closes on your paid page.'),
        'eyebrow': 'Live now · Reach',
        'h1_pre': 'Threads auto-reply bot for',
        'h1_accent': 'posts and comments.',
        'lede': [
            'Threads is public only, and that is the whole shape of it. Your persona posts, then '
            'answers the comments and mentions those posts collect, in the same voice she uses '
            'everywhere else.',
            'Replies are what keep a Threads post alive. Answering them within minutes, every time, '
            'is the part no creator does by hand for long.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Public reach only. Threads has no DMs, so the funnel runs on Telegram, Discord or X.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'She posts', 'detail': 'Sent from the console or planned a week ahead on the content calendar.'},
            {'label': 'Comments arrive', 'detail': 'Replies and mentions are picked up automatically while you are asleep.'},
            {'label': 'She answers in character', 'detail': 'Every reply is written for that comment, in the voice from the builder.'},
            {'label': 'The bio link does the rest', 'detail': 'A tracked link hands the fan to a channel that has a DM funnel.'},
        ],
        'route_foot': 'Threads fills the funnel. <b>Telegram, Discord or X closes it.</b>',
        'features_eyebrow': 'What it does',
        'features_h2_pre': 'The replies are',
        'features_h2_accent': 'the whole channel',
        'features_sub': ('A post with twenty answered comments outruns a post with twenty ignored ones. '
                         'That is the entire mechanic, and it runs on its own.'),
        'features': [
            {'icon': '📝', 'title': 'Posts in her voice',
             'body': 'Write from the console or plan the week on the calendar alongside X, Instagram and Fanvue.'},
            {'icon': '💬', 'title': 'Replies to comments',
             'body': 'Comments on her own posts get an in-character answer, which is what keeps the post moving.'},
            {'icon': '🔔', 'title': 'Answers mentions',
             'body': 'Mentions are picked up too, so a conversation about her does not carry on without her.'},
            {'icon': '🎚️', 'title': 'Switchable per loop',
             'body': 'Comment replies and mention replies are separate switches. Start with one and add the other.'},
            {'icon': '📜', 'title': 'Live activity log',
             'body': 'Every round is logged as it happens, so you can read exactly what she said before you leave it running.'},
            {'icon': '🛰️', 'title': 'Always on',
             'body': 'Runs server side and stays on through deploys. No open tab and no machine left running.'},
        ],
        'how_h2_pre': 'Connected in',
        'how_h2_accent': 'three steps',
        'how_sub': 'One switch to post, one to answer, and a calendar behind both.',
        'steps': [
            {'title': 'Build the persona', 'body': 'The same identity and voice every other channel uses comes from the visual builder.'},
            {'title': 'Connect Threads', 'body': 'Connect her account from the dashboard. Posting and replies run off the same connection.'},
            {'title': 'Start auto-reply', 'body': 'Switch on comment replies, mention replies, or both, and watch the log for the first few rounds.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Threads against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Threads is reach with a conversation attached, but the conversation is public and it stays public.',
        'rows': [
            {'k': 'Threads', 'v': 'Public only, no DMs. Posting plus comment and mention auto-reply.'},
            {'k': 'X (Twitter)', 'v': 'The same public work plus a full DM funnel and lead gathering.'},
            {'k': 'Instagram', 'v': 'Posting only. Feed, Stories and Reels on a schedule, with no replies at all.'},
            {'k': 'Telegram and Discord', 'v': 'Where a public follower becomes a private conversation and then a subscriber.'},
            {'k': 'Fanvue', 'v': 'The destination. The same persona keeps selling inside that inbox after the fan pays.'},
        ],
        'faq': [
            {'q': 'Can she DM on Threads?',
             'a': 'No. Threads has no DMs, so there is no funnel here. Public reach is the job, and a tracked bio link hands fans to a channel that does have one.'},
            {'q': 'Does she reply to every comment?',
             'a': 'To the ones on her own posts, and to mentions, and only for the loops you switch on. You can run comments without mentions or the other way around.'},
            {'q': 'Will the replies read like a bot?',
             'a': 'They are generated for that comment in the voice you configured, with the same sentence length, punctuation and emoji rules the persona uses everywhere else.'},
            {'q': 'Can I schedule posts?',
             'a': 'Yes. Threads is one of the channels the content planner publishes to automatically.'},
            {'q': 'Do I need a tab open?',
             'a': 'No. It runs server side and stays on through deploys.'},
            {'q': 'How do fans get into the funnel?',
             'a': 'Through a tracked link in her bio. Every fan it sends is credited to Threads, and you can change where it points later without editing the bio.'},
        ],
        'related': _related('threads-auto-reply', ['x-ai-bot', 'instagram-posting-automation', 'ai-content-planner', 'telegram-ai-chatbot']),
        'close_h2': 'Never leave a comment unanswered again',
        'close_sub': 'She posts, she answers, and the post keeps moving while you are doing something else.',
    },

    'velvetchat-share-link': {
        'slug': 'velvetchat-share-link',
        'live': True,
        'title': 'AI Chat Page and Embed for Creators | Velvetchat',
        'description': ('Give your persona her own chat page on a link you own. Share it anywhere, embed '
                        'it on your site, and run the full funnel on property no platform can take away.'),
        'eyebrow': 'Live now · Your own property',
        'h1_pre': 'Your own AI chat page,',
        'h1_accent': 'on a link you control.',
        'lede': [
            'Every persona gets a Velvetchat page: a chat your fans open in a browser, with no app to '
            'install, no account to make and no platform in the middle.',
            'It is the one channel nobody can suspend. Share the link where a paysite URL would get '
            'filtered, or embed the chat straight into your own site and keep the traffic.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'A direct link to share, or an embed snippet to paste. Both take about a minute.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'You share the link', 'detail': 'In a bio, a Story, a Reddit profile, anywhere a paysite URL would be blocked.'},
            {'label': 'The fan opens the chat', 'detail': 'A browser page, no signup, no install, her voice from the first message.'},
            {'label': 'The funnel runs', 'detail': 'Warm, engage, intrigue, tease, offer, close, at the pace you set in the builder.'},
            {'label': 'They land on your paid page', 'detail': 'Every fan credited to the link that sent them.'},
        ],
        'route_foot': 'The only channel that <b>cannot be taken away from you.</b>',
        'features_eyebrow': 'What it does',
        'features_h2_pre': 'A funnel on',
        'features_h2_accent': 'property you own',
        'features_sub': ('Every other channel is rented. This one is a page on your own domain or ours, with '
                         'the same persona and the same funnel behind it.'),
        'features': [
            {'icon': '🔗', 'title': 'A direct link',
             'body': 'One URL per persona. Put it anywhere, including the places that filter paysite domains.'},
            {'icon': '🧩', 'title': 'Embeds on your site',
             'body': 'Copy the snippet, paste it into your page, and the chat runs inside your own layout.'},
            {'icon': '🎨', 'title': 'Her landing page too',
             'body': 'Each persona also gets a profile page with her photos and the chat already embedded, if you would rather not build one.'},
            {'icon': '💬', 'title': 'The full funnel',
             'body': 'Same six stages, same memory, same voice as Telegram and Discord. Nothing is cut down for the web.'},
            {'icon': '📱', 'title': 'No app, no signup',
             'body': 'A fan taps the link and is talking to her. Every step between a link and a conversation loses people.'},
            {'icon': '🏷️', 'title': 'Labelled as an AI chat',
             'body': 'Chats hosted on your Velvetchat page are labelled, which is what keeps this channel safe to advertise anywhere.'},
        ],
        'how_h2_pre': 'Live in',
        'how_h2_accent': 'three steps',
        'how_sub': 'No hosting, no domain setup, no code beyond one paste.',
        'steps': [
            {'title': 'Build the persona', 'body': 'Her identity, voice and funnel pacing come from the visual builder, the same as every other channel.'},
            {'title': 'Copy the link', 'body': 'Open Share Your Chat in the dashboard and take the direct link, or the embed snippet.'},
            {'title': 'Put it where the fans are', 'body': 'A bio, a Story, a pinned post, or your own website. Traffic from each is credited separately.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Velvetchat against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Use it where a platform link will not survive, and as the fallback for the day one of them changes its mind.',
        'rows': [
            {'k': 'Velvetchat', 'v': 'Your own page and embed. No platform in the middle, no account to lose, full funnel.'},
            {'k': 'Telegram', 'v': 'The strongest converting channel, but it needs the fan to have Telegram.'},
            {'k': 'Discord', 'v': 'DM funnel inside communities she already belongs to.'},
            {'k': 'Reddit and other filtered places', 'v': 'Where a known paysite domain gets removed, a Velvetchat link does not.'},
            {'k': 'Fanvue', 'v': 'The destination. Velvetchat warms the fan, Fanvue takes the money.'},
        ],
        'faq': [
            {'q': 'Do fans need an account?',
             'a': 'No. They open the link and start talking. No install, no signup, no email.'},
            {'q': 'Can I put it on my own website?',
             'a': 'Yes. Copy the embed snippet and paste it into your page. The chat runs inside your own layout.'},
            {'q': 'Does the full funnel run here?',
             'a': 'Yes. Same six stages, same memory, same persona voice as the messaging platforms.'},
            {'q': 'Why would I use this instead of Telegram?',
             'a': 'Use both. Velvetchat is what you share where a paysite link gets filtered, and what you still own if a platform suspends an account.'},
            {'q': 'Is it obvious that it is AI?',
             'a': 'Chats hosted here are labelled as an AI chat. That is deliberate, and it is what makes the link safe to put in public places.'},
            {'q': 'Can I track where fans came from?',
             'a': 'Yes. Traffic from each link is credited separately, so you can see which channel actually sends buyers.'},
        ],
        'related': _related('velvetchat-share-link', ['telegram-ai-chatbot', 'discord-ai-chatbot', 'fanvue-ai-chatter', 'x-ai-bot']),
        'close_h2': 'Own one channel outright',
        'close_sub': 'Every other platform is rented. This is the page that is still yours on the day one of them changes the rules.',
    },

    'ai-content-planner': {
        'slug': 'ai-content-planner',
        'live': True,
        'title': 'AI Content Planner for Creators | Velvetfunnel',
        'description': ('Plan a week of posts across X, Threads, Instagram and Fanvue from one calendar. '
                        'The AI writes them in your persona\'s voice, attaches your media and posts on time.'),
        'eyebrow': 'Live now · Tool',
        'h1_pre': 'AI content planner for',
        'h1_accent': 'every channel at once.',
        'lede': [
            'One calendar, one persona, every channel. Plan the week, let the AI write the posts in '
            'her voice, attach media from your vault, and each post fires at its slot.',
            'X, Threads, Instagram and Fanvue publish automatically. Channels with no posting API '
            'stay on the calendar as a reminder to post by hand, so nothing quietly disappears.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Plan the week in one click, then edit anything you do not like before it goes out.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'Pick the week and the channels', 'detail': 'One persona at a time, with the channels she is connected to already offered.'},
            {'label': 'Plan it', 'detail': 'The AI lays out the week and writes every post, or you write them yourself.'},
            {'label': 'Edit and attach', 'detail': 'Change the words, set the rating, pick media from your Fanvue vault.'},
            {'label': 'It posts on time', 'detail': 'Each slot fires on its own. Failures are shown rather than swallowed.'},
        ],
        'route_foot': 'Posting is the reach half. <b>The DM funnel is the money half.</b>',
        'features_eyebrow': 'What it does',
        'features_h2_pre': 'A week of content',
        'features_h2_accent': 'in one sitting',
        'features_sub': ('The planner knows what each channel accepts, so a post is shaped for its platform '
                         'before it is queued rather than rejected at the slot.'),
        'features': [
            {'icon': '🗓️', 'title': 'Plan the whole week',
             'body': 'One button lays out the week across the channels you pick, and you edit whatever you want before it fires.'},
            {'icon': '✍️', 'title': 'Written in her voice',
             'body': 'Every caption comes from the persona builder, not a generic content tool. Set a post to safe or explicit, or let the persona setting decide.'},
            {'icon': '🔁', 'title': 'Cross-post or tailor',
             'body': 'Send the same post everywhere, or let each channel get its own version of the idea.'},
            {'icon': '🖼️', 'title': 'Media from your vault',
             'body': 'Browse your Fanvue vault from inside the planner and attach real content to a post without downloading anything.'},
            {'icon': '🎛️', 'title': 'Per-channel options',
             'body': 'Feed post, Story or Reel on Instagram. Audience and unlock price on Fanvue. Subreddit, flair and stagger on Reddit.'},
            {'icon': '📊', 'title': 'Queue you can see',
             'body': 'Queued, sending, posted, failed and manual all show on the grid, with the counts above it.'},
        ],
        'how_h2_pre': 'Planned in',
        'how_h2_accent': 'three steps',
        'how_sub': 'It reads the connections you already have and only offers the channels that can post.',
        'steps': [
            {'title': 'Pick the persona', 'body': 'The calendar is per persona, so two personas never end up posting the same words on the same day.'},
            {'title': 'Plan the week', 'body': 'Choose the channels, decide whether one post goes everywhere, and let it fill the week.'},
            {'title': 'Edit and leave it', 'body': 'Change the words, the time, the media or the rating. Anything you do not touch goes out as written.'},
        ],
        'rows_eyebrow': 'What publishes',
        'rows_h2_pre': 'Which channels',
        'rows_h2_accent': 'post on their own',
        'rows_sub': 'A channel with a posting API fires by itself. A channel without one stays on the calendar as a manual row rather than pretending.',
        'rows': [
            {'k': 'X (Twitter)', 'v': 'Publishes automatically at the slot, with media.'},
            {'k': 'Threads', 'v': 'Publishes automatically at the slot.'},
            {'k': 'Instagram', 'v': 'Publishes automatically as a feed post, a Story or a Reel, whichever you picked.'},
            {'k': 'Fanvue', 'v': 'Publishes to the feed with the audience and unlock price you set. A priced post needs media behind it.'},
            {'k': 'Reddit and TikTok', 'v': 'Built and waiting on access. A planned post for either comes back as a manual row on the calendar for now.'},
        ],
        'faq': [
            {'q': 'Does the AI write the posts or do I?',
             'a': 'Either. Plan the week and it writes all of them, or write your own and use it purely as a calendar. Anything it writes can be edited before it goes out.'},
            {'q': 'Can I send the same post to every channel?',
             'a': 'Yes, there is a switch for it. Leave it off and each channel gets its own version, which is usually better for reach.'},
            {'q': 'What happens to channels that cannot post automatically?',
             'a': 'They sit on the calendar as a manual row with the text and media ready, so you post them by hand instead of forgetting them.'},
            {'q': 'Where does the media come from?',
             'a': 'Your Fanvue vault, browsed from inside the planner. Nothing is downloaded or re-uploaded by hand.'},
            {'q': 'Can I set a post as explicit?',
             'a': 'Per post, yes: safe, explicit, or whatever the persona is set to. Channels that must stay safe for work are held there whatever the post says.'},
            {'q': 'What if a post fails?',
             'a': 'It shows as failed on the grid with the reason, rather than disappearing. Fanvue connections missing the posting permission are flagged when you queue, not hours later at the slot.'},
        ],
        'related': _related('ai-content-planner', ['x-ai-bot', 'instagram-posting-automation', 'threads-auto-reply', 'ai-image-generator']),
        'close_h2': 'Stop posting channel by channel',
        'close_sub': 'One calendar, one persona, every channel she is on, written in her voice and out the door on time.',
    },

    'ai-image-generator': {
        'slug': 'ai-image-generator',
        'live': False,
        'title': 'AI Image and Video Generator for Creators | Velvetfunnel',
        'description': ('Generate photos and short clips of your own persona from her reference shots. '
                        'Consistent face and body, safe or explicit, priced per generation in tokens.'),
        'eyebrow': 'In testing · Tool',
        'h1_pre': 'AI image and video generator for',
        'h1_accent': 'your own persona.',
        'lede': [
            'The Generation Studio makes new photos of a persona who already exists. You give her a '
            'set of face shots and a set of body shots, and every generation is conditioned on them, '
            'so it is the same woman in every frame rather than a new one each time.',
            'Short clips work the same way with one rule: a clip is only ever animated from a photo '
            'you already kept, so its first frame carries her face and there is nothing to correct.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'In testing with a small group. Everything below is built and running on the platform now.',
        'route_title': 'The route, end to end',
        'route': [
            {'label': 'Pick the model', 'detail': 'Photo or video, safe or explicit. The choice filters the models that can do it.'},
            {'label': 'Pick her face and body', 'detail': 'Reference shots from her own library, kept as two separate sets.'},
            {'label': 'Describe the shot', 'detail': 'A scene from the list, your own words on top, and anything to keep out of frame.'},
            {'label': 'Keep what works', 'detail': 'Results land unapproved. Keep the good ones, drop the rest, and only kept media can reach a fan.'},
        ],
        'route_foot': 'Nothing unreviewed ever reaches a fan. <b>That is enforced, not a setting.</b>',
        'features_eyebrow': 'What it does',
        'features_h2_pre': 'The same woman,',
        'features_h2_accent': 'every single time',
        'features_sub': ('Identity is the hard part of this and it is never left to the prompt. Every generation '
                         'is conditioned on her real reference shots.'),
        'features': [
            {'icon': '🧍', 'title': 'Face and body, separately',
             'body': 'Two reference sets per persona. A full-body shot is exactly where a face reference alone starts to drift, so the body gets its own.'},
            {'icon': '🎬', 'title': 'Clips from a kept photo',
             'body': 'Video always starts from a still you already approved. There is no text-to-video path, on purpose.'},
            {'icon': '🎚️', 'title': 'Safe or explicit',
             'body': 'The rating filters the model list. Explicit work is pinned to the one model that serves it, rather than left to fail at the provider.'},
            {'icon': '🖼️', 'title': 'Scene builder',
             'body': 'Start from a scene, add your own description, and list what to keep out of the shot. A safety baseline is always applied underneath.'},
            {'icon': '✅', 'title': 'Review before anything ships',
             'body': 'Generations land unapproved and are invisible to every send path until you keep them. Unkept media expires on its own.'},
            {'icon': '💳', 'title': 'Priced per generation',
             'body': 'Credits are pegged to what the generation actually costs, so the price is the same maths for every model and every size.'},
        ],
        'how_h2_pre': 'Generated in',
        'how_h2_accent': 'three steps',
        'how_sub': 'No prompt engineering, no LoRA training, no model to fine-tune.',
        'steps': [
            {'title': 'Give her references', 'body': 'Upload or pick her face shots and her body shots once. Every later generation uses them.'},
            {'title': 'Set the shot', 'body': 'Photo or clip, safe or explicit, size, how many, the scene and your own description.'},
            {'title': 'Keep the good ones', 'body': 'Review the batch, keep what works, and it becomes available to the rest of the platform.'},
        ],
        'rows_eyebrow': 'The models',
        'rows_h2_pre': 'What runs',
        'rows_h2_accent': 'behind it',
        'rows_sub': 'Different models are good at different things. The rating and the format pick the shortlist so you do not have to.',
        'rows': [
            {'k': 'Seedream 4.5', 'v': 'Every explicit still. The one model that serves explicit work and takes reference images, which is why it is pinned there.'},
            {'k': 'Seedream 5.0 Pro', 'v': 'Safe for work only. Its provider refuses explicit prompts outright, so it is never offered for them.'},
            {'k': 'Nano Banana Pro and Nano Banana 2', 'v': 'Safe for work only, for the shots where their look is the better one.'},
            {'k': 'Video', 'v': 'Clips animated from an approved still, priced by length and size.'},
            {'k': 'Sizes', 'v': 'Two bands, roughly 2k and 4k, resolved per model because each one accepts its own dimensions.'},
        ],
        'faq': [
            {'q': 'Is it available yet?',
             'a': 'Not to every creator. It is in testing with a small group while the pricing and the review flow settle. Everything described here is built and running.'},
            {'q': 'How does it keep the same face?',
             'a': 'Every generation is conditioned on her real reference photos, and the face set and the body set are kept apart. Identity is never left to the wording of a prompt.'},
            {'q': 'Can I generate a video from text?',
             'a': 'No, deliberately. A clip is animated from a still you already approved, so the first frame is already her.'},
            {'q': 'Can it generate explicit content?',
             'a': 'Yes, on the one model that serves it. The safe-for-work models refuse it at the provider, so they are filtered out before you can pick them.'},
            {'q': 'Can a generation reach a fan by accident?',
             'a': 'No. A new generation is unapproved and invisible to every send path until you keep it, and anything you do not keep expires on its own.'},
            {'q': 'What does it cost?',
             'a': 'Credits, priced from what the generation actually costs to run, so a still and a five second clip are very different numbers. The studio shows the price before you submit.'},
        ],
        'related': _related('ai-image-generator', ['ai-content-planner', 'fanvue-ai-chatter', 'telegram-ai-chatbot', 'velvetchat-share-link']),
        'close_h2': 'New photos of a persona who already exists',
        'close_sub': 'Her face, her body, a new scene, and a review step between the model and your fans.',
    },

    'onlyfans-ai-chatbot': {
        'slug': 'onlyfans-ai-chatbot',
        'live': False,
        'title': 'OnlyFans AI Chatbot & PPV Automation | Velvetfunnel',
        'description': ('An AI chatter for your OnlyFans inbox. Automated replies in your persona\'s voice, '
                        'PPV delivery and fan scoring, running the same funnel as every other channel.'),
        'eyebrow': 'In production · Paid destination',
        'h1_pre': 'OnlyFans AI chatbot and',
        'h1_accent': 'PPV automation.',
        'lede': [
            'OnlyFans is the second paid page Velvetfunnel funnels into. The console, the connection '
            'and the reply loop are built and tested. It is not switched on for creators yet, and '
            'the sign-up says so rather than pointing you at a connection you cannot finish.',
            'When it opens, it works the way Fanvue already does: the same persona, the same memory '
            'and the same funnel keep running inside your subscriber inbox after a fan pays.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Not connectable yet. Start on Fanvue or your own Velvetchat page and switch the destination later.',
        'route_title': 'Where OnlyFans will sit',
        'route': [
            {'label': 'Traffic arrives', 'detail': 'Telegram, Discord, X, Instagram and Threads build the audience.'},
            {'label': 'The funnel warms them', 'detail': 'Your persona works the DM until the fan is ready to pay.'},
            {'label': 'They subscribe', 'detail': 'The CTA lands them on your paid page, credited to the channel that found them.'},
            {'label': 'PPV starts earning', 'detail': 'The same persona works the subscriber inbox and sells from your vault.'},
        ],
        'route_foot': 'You pick the destination per persona, and <b>change it later without touching a bio.</b>',
        'features_eyebrow': 'What is built',
        'features_h2_pre': 'The same inbox work,',
        'features_h2_accent': 'on a second paid page',
        'features_sub': ('Everything here exists in the platform today. What is missing is the switch that '
                         'offers it to creators, and that is a release decision rather than a build.'),
        'features': [
            {'icon': '💬', 'title': 'Inbox auto-reply',
             'body': 'Incoming subscriber messages answered in character, around the clock, with the memory the fan already built up before they paid.'},
            {'icon': '💰', 'title': 'PPV delivery',
             'body': 'Paid content sent in conversation at the moment a fan is warmest, rather than blasted to a list.'},
            {'icon': '🔐', 'title': 'Hosted sign-in',
             'body': 'She connects through the same hosted sign-in browser Discord and Instagram use, so the 2FA and the device check are handled by the platform itself.'},
            {'icon': '🧠', 'title': 'One persona across the paywall',
             'body': 'The voice a fan subscribed to is the voice waiting inside, with the same memory of what they already talked about.'},
            {'icon': '🎚️', 'title': 'Its own pacing',
             'body': 'Paid inboxes are paced separately from cold DMs, so she reads right for somebody who has already bought.'},
            {'icon': '📈', 'title': 'Funnel analytics',
             'body': 'Funnel stage per fan and what each PPV drop earned, the same reporting Fanvue already has.'},
        ],
        'how_h2_pre': 'What happens',
        'how_h2_accent': 'in the meantime',
        'how_sub': 'Nothing you build now has to be redone when this opens.',
        'steps': [
            {'title': 'Build the persona now', 'body': 'Her identity, voice and funnel pacing are shared by every channel and every destination. None of it is per platform.'},
            {'title': 'Run the funnel to Fanvue', 'body': 'Or to your own Velvetchat page. The social channels do not care which one they point at.'},
            {'title': 'Switch the destination later', 'body': 'The paid page is set per persona, so moving it is one change rather than editing every bio you have.'},
        ],
        'rows_eyebrow': 'The destination',
        'rows_h2_pre': 'Where your funnel',
        'rows_h2_accent': 'can land',
        'rows_sub': 'The funnel is built to land anywhere. These are the paid pages in the plan.',
        'rows': [
            {'k': 'Fanvue', 'v': 'Live today. Subscriber inbox auto-reply, PPV from your vault, fan scoring and funnel analytics.'},
            {'k': 'OnlyFans', 'v': 'In production. Console, connection and reply loop built and tested, waiting on release.'},
            {'k': 'Fansly', 'v': 'Planned. Next after OnlyFans, on the same funnel and the same persona.'},
            {'k': 'Velvetchat', 'v': 'Live today. Your own chat page, for channels where a paysite link would be filtered.'},
            {'k': 'Per persona routing', 'v': 'Each persona sends fans to the page you choose, changed later without editing a single bio.'},
        ],
        'faq': [
            {'q': 'Can I connect OnlyFans today?',
             'a': 'No. It shows as coming soon in the dashboard rather than offering a connection that is not open yet. Fanvue and Velvetchat are the live destinations.'},
            {'q': 'How much of it is actually built?',
             'a': 'The console, the connection, the transport and the reply loop are all in the platform and tested. What is left is the release decision to offer it.'},
            {'q': 'Will I have to rebuild my persona for it?',
             'a': 'No. Persona identity, voice and funnel pacing are shared across every channel and every paid destination.'},
            {'q': 'Will it send PPV automatically?',
             'a': 'Yes, the same way Fanvue does today: from the folders you allow, at the price bands you set, tracked so nothing goes twice to the same fan.'},
            {'q': 'What should I use until then?',
             'a': 'Point the funnel at Fanvue, or at your own Velvetchat page. Changing the destination later is one setting per persona.'},
            {'q': 'Will Fansly work the same way?',
             'a': 'That is the plan. Same funnel, same persona, same vault logic, with the destination picked per persona.'},
        ],
        'related': _related('onlyfans-ai-chatbot', ['fanvue-ai-chatter', 'fansly-ai-chatbot', 'telegram-ai-chatbot', 'velvetchat-share-link']),
        'close_h2': 'Build the funnel now, point it anywhere later',
        'close_sub': 'Nothing you set up today is tied to one paid page. The destination is one setting per persona.',
    },

    'fansly-ai-chatbot': {
        'slug': 'fansly-ai-chatbot',
        'live': False,
        'title': 'Fansly AI Chatbot & PPV Automation | Velvetfunnel',
        'description': ('Fansly is a planned paid destination for the Velvetfunnel funnel. Same persona, '
                        'same funnel, same PPV automation. Run it to Fanvue today and switch later.'),
        'eyebrow': 'Planned · Paid destination',
        'h1_pre': 'Fansly AI chatbot and',
        'h1_accent': 'PPV automation.',
        'lede': [
            'Fansly is on the roadmap as a paid destination, after OnlyFans. It is not connectable '
            'yet and nothing on this page is claiming otherwise.',
            'It matters anyway, because of how the platform is put together. Your persona, her voice, '
            'her memory and the funnel that warms fans up are not tied to any one paid page, so a '
            'funnel you build today points at Fansly the day it opens.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Not connectable yet. Everything you build now carries over when it is.',
        'route_title': 'Where Fansly will sit',
        'route': [
            {'label': 'Traffic arrives', 'detail': 'Telegram, Discord, X, Instagram and Threads build the audience.'},
            {'label': 'The funnel warms them', 'detail': 'Your persona works the DM until the fan is ready to pay.'},
            {'label': 'They subscribe', 'detail': 'On whichever paid page that persona is pointed at.'},
            {'label': 'PPV starts earning', 'detail': 'The same persona keeps working the subscriber inbox.'},
        ],
        'route_foot': 'The destination is <b>one setting per persona</b>, not a rebuild.',
        'features_eyebrow': 'Why it is worth knowing',
        'features_h2_pre': 'Nothing you build now',
        'features_h2_accent': 'is tied to one paysite',
        'features_sub': ('Creators who earn on more than one page usually end up maintaining two setups. The '
                         'whole point of this architecture is that you do not.'),
        'features': [
            {'icon': '🧩', 'title': 'One persona, any destination',
             'body': 'Identity, voice, memory and funnel pacing live with the persona, not with the paid page she sends fans to.'},
            {'icon': '🔀', 'title': 'Switch without editing bios',
             'body': 'Every social channel points at a tracked link. Change where it lands and every bio you already wrote keeps working.'},
            {'icon': '📣', 'title': 'The traffic side is live now',
             'body': 'Telegram, Discord, X, Instagram and Threads are all running today, whatever you end up funnelling into.'},
            {'icon': '💰', 'title': 'The same PPV logic',
             'body': 'Vault selling, per-fan tracking so nothing is sent twice, fan scoring and funnel analytics are already built on Fanvue.'},
            {'icon': '🗓️', 'title': 'The content side too',
             'body': 'The content planner and the persona builder are destination-agnostic. They do not change when a new paid page is added.'},
            {'icon': '🛠️', 'title': 'Ordered honestly',
             'body': 'OnlyFans comes first because it is built and waiting on release. Fansly follows it, and the dashboard says exactly that.'},
        ],
        'how_h2_pre': 'What to do',
        'how_h2_accent': 'in the meantime',
        'how_sub': 'None of this is throwaway work.',
        'steps': [
            {'title': 'Build the persona', 'body': 'Her identity, voice and funnel pacing in the visual builder. Shared by every channel and every destination.'},
            {'title': 'Turn on the traffic channels', 'body': 'Telegram, Discord, X, Instagram and Threads are live today and fill the funnel whatever it lands on.'},
            {'title': 'Point at a live destination', 'body': 'Fanvue, or your own Velvetchat page. Move it to Fansly later with one change.'},
        ],
        'rows_eyebrow': 'The destination',
        'rows_h2_pre': 'Where your funnel',
        'rows_h2_accent': 'can land',
        'rows_sub': 'Two live today, two in the plan. The funnel in front of them is the same either way.',
        'rows': [
            {'k': 'Fanvue', 'v': 'Live. Inbox auto-reply, PPV from your vault, fan scoring and funnel analytics.'},
            {'k': 'Velvetchat', 'v': 'Live. Your own chat page and embed, on a link no platform controls.'},
            {'k': 'OnlyFans', 'v': 'In production. Built and tested, waiting on release.'},
            {'k': 'Fansly', 'v': 'Planned, after OnlyFans. Not connectable yet.'},
            {'k': 'Per persona routing', 'v': 'Each persona sends fans to the page you choose, changed later without editing a single bio.'},
        ],
        'faq': [
            {'q': 'Can I connect Fansly today?',
             'a': 'No. It shows as coming soon in the dashboard. Fanvue and your own Velvetchat page are the live destinations.'},
            {'q': 'When will it be ready?',
             'a': 'After OnlyFans, which is built and waiting on release. There is no date on this page because there is no date worth putting on it.'},
            {'q': 'Is any of it built yet?',
             'a': 'The funnel, the persona system, the traffic channels and the PPV logic are all built and running against Fanvue. The Fansly connection itself is not.'},
            {'q': 'Will I have to redo my setup?',
             'a': 'No. The paid page is one setting per persona. Everything in front of it is shared.'},
            {'q': 'Can I run two paid pages at once?',
             'a': 'You can point different personas at different destinations. One persona sends fans to one page at a time.'},
            {'q': 'What should I use meanwhile?',
             'a': 'Fanvue if you earn there, or Velvetchat if you want the funnel landing on a page you own outright.'},
        ],
        'related': _related('fansly-ai-chatbot', ['fanvue-ai-chatter', 'onlyfans-ai-chatbot', 'velvetchat-share-link', 'telegram-ai-chatbot']),
        'close_h2': 'Start the funnel before the destination opens',
        'close_sub': 'The traffic channels are live today, and the paid page they land on is one setting away from being a different one.',
    },

    'reddit-posting-bot': {
        'slug': 'reddit-posting-bot',
        'live': False,
        'title': 'Reddit Posting Bot for Creators | Velvetfunnel',
        'description': ('Plan one post and it becomes a post per subreddit, each with its own title, flair '
                        'and slot, staggered so it does not read as spam. In production, waiting on access.'),
        'eyebrow': 'In production · Reach',
        'h1_pre': 'Reddit posting bot for',
        'h1_accent': 'one post per subreddit.',
        'lede': [
            'Reddit is built, tested and in the platform. It is not switched on, and the reason is at '
            'Reddit\'s end rather than ours: self-serve app creation is closed and API access is now a '
            'manual approval. The dashboard says coming soon instead of offering a connection that '
            'cannot be completed.',
            'When it opens, it is a registered Reddit app with a token that does not expire, which is '
            'the shape worth having on a platform that removes accounts for looking automated.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Not connectable yet. A planned Reddit post stays on your calendar as a manual row in the meantime.',
        'route_title': 'How a Reddit post works',
        'route': [
            {'label': 'You plan one post', 'detail': 'One idea, one piece of media, on the content planner calendar.'},
            {'label': 'It becomes several', 'detail': 'One row per subreddit, each with its own title, flair and slot.'},
            {'label': 'They go out staggered', 'detail': 'Minutes apart by default. The same words in four subreddits at once is what a spam filter is built to catch.'},
            {'label': 'She answers the comments', 'detail': 'In character, with no link, no CTA and no URL. A subreddit is the fastest place to lose an account over one.'},
        ],
        'route_foot': 'Public threads never carry an offer. <b>That is enforced, not a setting.</b>',
        'features_eyebrow': 'What is built',
        'features_h2_pre': 'Built for how',
        'features_h2_accent': 'Reddit actually works',
        'features_sub': ('Reddit punishes the things every other scheduler does by default. The differences here '
                         'are all deliberate.'),
        'features': [
            {'icon': '🗂️', 'title': 'One post, many subreddits',
             'body': 'A single planned post becomes a row per subreddit, each with its own title and flair, because each community wants a different framing.'},
            {'icon': '⏱️', 'title': 'Staggered by default',
             'body': 'Minutes between subreddits, set per post. Simultaneous cross-posting is the pattern spam filters look for.'},
            {'icon': '🏷️', 'title': 'Flairs per community',
             'body': 'Flair is picked per subreddit from what that subreddit actually offers, so a post is not removed for missing one.'},
            {'icon': '💬', 'title': 'Comment replies without links',
             'body': 'She answers comments in character. No funnel, no offer, no CTA and no URL of any kind in a public thread.'},
            {'icon': '🔑', 'title': 'A registered app, not a browser',
             'body': 'Approve once and the refresh token does not expire. A declared app under Reddit\'s own developer terms rather than a client those terms forbid.'},
            {'icon': '📄', 'title': 'Image, video, text or link',
             'body': 'Pick the post type per plan, with the media handled for you.'},
        ],
        'how_h2_pre': 'What happens',
        'how_h2_accent': 'in the meantime',
        'how_sub': 'Planned Reddit posts are kept rather than dropped.',
        'steps': [
            {'title': 'Plan it anyway', 'body': 'Reddit posts still go on the calendar. They come back as a manual row with the text and media ready.'},
            {'title': 'Post it by hand', 'body': 'The planner gives you the words and the media. Nothing is lost while access is pending.'},
            {'title': 'It switches on later', 'body': 'When the app is approved, the same planned posts start firing on their own.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'Reddit against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'Reddit is reach with the strictest rules of any channel here, which is why it is shaped differently.',
        'rows': [
            {'k': 'Reddit', 'v': 'Per-subreddit posting with its own title and flair, staggered, plus comment replies that never carry a link.'},
            {'k': 'X (Twitter)', 'v': 'Posts, replies, DM funnel and lead gathering, all on one account.'},
            {'k': 'Instagram and Threads', 'v': 'Reach only, on a schedule, from the same calendar.'},
            {'k': 'Telegram and Discord', 'v': 'Where a Reddit reader becomes a private conversation and then a subscriber.'},
            {'k': 'Velvetchat', 'v': 'The link that survives Reddit filters, where a known paysite domain would be removed.'},
        ],
        'faq': [
            {'q': 'Can I connect Reddit today?',
             'a': 'No. Reddit closed self-serve app creation and API access is a manual approval now, so the dashboard shows it as coming soon rather than offering a dead connection.'},
            {'q': 'What happens to a Reddit post I plan?',
             'a': 'It stays on the calendar as a manual row with the text and media ready, so you post it by hand instead of losing it.'},
            {'q': 'Will she DM people on Reddit?',
             'a': 'Not in this release. Reddit Chat is a separate system from its API, and the posting and comment side is what is being shipped first.'},
            {'q': 'Will she post my paid link?',
             'a': 'Never in a public thread. Reddit removes known paysite domains and removes accounts that push them, so public comments carry no link, CTA or URL at all.'},
            {'q': 'Why one post per subreddit?',
             'a': 'Because each community wants a different title, a different flair and a different time. Identical simultaneous posts are exactly what gets filtered.'},
            {'q': 'What is needed to switch it on?',
             'a': 'An approved Reddit API client. The code, the OAuth flow and the posting transport are all built and tested already.'},
        ],
        'related': _related('reddit-posting-bot', ['ai-content-planner', 'velvetchat-share-link', 'x-ai-bot', 'tiktok-posting-automation']),
        'close_h2': 'Plan Reddit now, post it automatically later',
        'close_sub': 'The calendar keeps every Reddit post ready to go, and starts firing them the day the app is approved.',
    },

    'tiktok-posting-automation': {
        'slug': 'tiktok-posting-automation',
        'live': False,
        'title': 'TikTok Posting Automation for Creators | Velvetfunnel',
        'description': ('Schedule safe-for-work clips to TikTok from the same calendar as every other '
                        'channel. Built as a registered app, in production and waiting on release.'),
        'eyebrow': 'In production · Reach',
        'h1_pre': 'TikTok posting automation for',
        'h1_accent': 'safe-for-work clips.',
        'lede': [
            'TikTok is a top-of-funnel channel and Velvetfunnel treats it as exactly that. Clips go '
            'out on a schedule from the same calendar as every other channel, and nothing explicit '
            'and no paid link ever rides on it.',
            'It is built as a registered TikTok app with the Content Posting API, tested, and sitting '
            'in the platform. The dashboard shows it as coming soon rather than offering a connection '
            'before the release is ready.',
        ],
        'cta_primary': 'Start now',
        'hero_note': 'Not connectable yet. A planned TikTok post stays on your calendar as a manual row in the meantime.',
        'route_title': 'How a TikTok post works',
        'route': [
            {'label': 'You plan a clip', 'detail': 'On the same content calendar as X, Threads, Instagram and Fanvue.'},
            {'label': 'It uploads to her account', 'detail': 'Through TikTok\'s own Content Posting API, with a bearer token rather than a driven browser.'},
            {'label': 'It lands or it publishes', 'detail': 'In her drafts for her to publish, or straight to her profile once the app is audited.'},
            {'label': 'The bio link does the rest', 'detail': 'A tracked link hands the viewer to a channel with a DM funnel.'},
        ],
        'route_foot': 'Safe for work, always. <b>No paid link ever rides on TikTok.</b>',
        'features_eyebrow': 'What is built',
        'features_h2_pre': 'A reach channel',
        'features_h2_accent': 'kept deliberately clean',
        'features_sub': ('TikTok bars pointing anyone at adult content. Rather than leaving that to a setting, '
                         'the channel is held safe for work in the platform itself.'),
        'features': [
            {'icon': '🎬', 'title': 'Clips on a schedule',
             'body': 'TikTok sits on the same calendar as every other channel, so a week of content is still one sitting.'},
            {'icon': '🔒', 'title': 'Held safe for work',
             'body': 'An explicit post cannot be queued to TikTok whatever the persona is set to, and no paid link goes out on it.'},
            {'icon': '🔑', 'title': 'A registered app',
             'body': 'Login Kit and the Content Posting API with a bearer token. No driven browser, no captured cookie, no signature to forge.'},
            {'icon': '📥', 'title': 'Drafts or direct',
             'body': 'By default the clip lands in her TikTok drafts and she publishes it herself. Direct posting turns on once TikTok audits the app.'},
            {'icon': '🗣️', 'title': 'Says which one it did',
             'body': 'Posted and in her drafts are not the same claim, so the console and the calendar both say which happened.'},
            {'icon': '🔗', 'title': 'Tracked bio link',
             'body': 'Viewers who follow the link are credited to TikTok, so you can see whether it is actually sending anyone.'},
        ],
        'how_h2_pre': 'What happens',
        'how_h2_accent': 'in the meantime',
        'how_sub': 'Planned TikTok posts are kept rather than dropped.',
        'steps': [
            {'title': 'Plan it anyway', 'body': 'TikTok posts still go on the calendar and come back as a manual row with the clip ready.'},
            {'title': 'Post it by hand', 'body': 'Nothing is lost while the release is pending. The planner holds the clip and the caption.'},
            {'title': 'It switches on later', 'body': 'When it is released, the same planned posts start uploading on their own.'},
        ],
        'rows_eyebrow': 'Where it fits',
        'rows_h2_pre': 'TikTok against',
        'rows_h2_accent': 'the other channels',
        'rows_sub': 'The widest reach and the tightest rules. It is a way in, never a way to sell.',
        'rows': [
            {'k': 'TikTok', 'v': 'Posting only, safe for work, one clip per post. No DMs, no comment replies, no paid links.'},
            {'k': 'Instagram', 'v': 'Posting only too, but feed posts, Stories and Reels, and no safe-for-work lock.'},
            {'k': 'Threads', 'v': 'Public only, with comment and mention auto-reply on top of posting.'},
            {'k': 'X (Twitter)', 'v': 'Posts, replies, DM funnel and lead gathering, all on one account.'},
            {'k': 'Telegram and Discord', 'v': 'Where a viewer becomes a private conversation and then a subscriber.'},
        ],
        'faq': [
            {'q': 'Can I connect TikTok today?',
             'a': 'No. It shows as coming soon in the dashboard. The app, the OAuth and the posting transport are built and tested, and the release is what is pending.'},
            {'q': 'Will it post explicit content?',
             'a': 'No, and it cannot be made to. TikTok bars pointing anyone at adult content, so this channel is held safe for work in the platform itself.'},
            {'q': 'Will it put my paid link on TikTok?',
             'a': 'No. No paid link rides on this channel. Traffic goes through a tracked bio link to a channel that can actually run a funnel.'},
            {'q': 'Does it post straight to her profile?',
             'a': 'The default uploads to her TikTok drafts and she taps publish, picking the privacy herself. Direct posting to the profile needs TikTok to audit the app first.'},
            {'q': 'Can it reply to comments or DMs?',
             'a': 'No. TikTok has no comment API, and there is no DM path here. It is a posting channel.'},
            {'q': 'What happens to a TikTok post I plan now?',
             'a': 'It stays on the calendar as a manual row with the clip and caption ready, so you post it by hand rather than losing it.'},
        ],
        'related': _related('tiktok-posting-automation', ['instagram-posting-automation', 'ai-content-planner', 'reddit-posting-bot', 'threads-auto-reply']),
        'close_h2': 'Plan TikTok now, upload it automatically later',
        'close_sub': 'The calendar keeps every clip ready to go, and starts uploading them the day the channel opens.',
    },
}

for _slug, _page in PAGES.items():
    _page['faq_schema'] = _faq_schema(_page['faq'])
