# Cuts each H3 weight under $src into 2 GB parts and writes h3.Dockerfile with
# one COPY --link layer per part: Docker pushes and pulls a layer as one stream,
# so many small layers fill the line where one 27 GB layer cannot.
# start/h3-gv.sh joins the parts back at boot.
param([string]$src = 'E:\h3', [string]$out = 'h3.Dockerfile')
$ErrorActionPreference = 'Stop'
$size = 2GB
$parts = Join-Path $src 'parts'
$lines = @('# syntax=docker/dockerfile:1.7', '# Generated by h3_split.ps1.', 'FROM runpod/worker-comfyui:5.10.0-base')
$buf = New-Object byte[] (64MB)
Get-ChildItem $src -Recurse -Filter *.safetensors | Where-Object { $_.FullName -notlike "$parts*" } | ForEach-Object {
    $rel = $_.FullName.Substring($src.TrimEnd('\').Length + 1).Replace('\', '/')
    $folder = Split-Path $rel -Parent
    New-Item -ItemType Directory -Force (Join-Path $parts $folder) | Out-Null
    $in = [IO.File]::OpenRead($_.FullName)
    $n = 0
    while ($in.Position -lt $in.Length) {
        $name = '{0}.part{1:D3}' -f $rel, $n
        $dest = Join-Path $parts $name
        $want = [Math]::Min($size, $in.Length - $in.Position)
        if ((Test-Path $dest) -and (Get-Item $dest).Length -eq $want) {
            $in.Seek($want, 'Current') | Out-Null
        } else {
            $o = [IO.File]::Create($dest); $left = $want
            while ($left -gt 0) { $r = $in.Read($buf, 0, [Math]::Min($buf.Length, $left)); $o.Write($buf, 0, $r); $left -= $r }
            $o.Close()
        }
        $lines += "COPY --link parts/$name /h3parts/$name"
        $n++
    }
    $in.Close()
    Write-Host "split $rel into $n parts"
}
$lines | Set-Content -Encoding ascii $out
